### ISSUE TITLE
VM complétude de prospection par maille - TOUTES SAISONS (all data)

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#1]
### Complétude de prospection (%)
**= nb d’espèces contactées sur la période actuelle / nb d’espèces de référence** 
:warning: En ne travaillant que sur les espèces en commun

:arrow_right_hook: Découle des VM espèces actuelles et espèces de référence par maille (TOUTES SAISONS)
:information_source: Champs : 
- id_maille
- nb espèces actuelles
- nb espèces de référence
- % de complétude

:recycle: Rafraîchissement 2 fois par jour

**Comment by lpofredc** [comment]
Done in #30

**Comment by lpofredc** [comment]
Le % de complétude doit être basé sur une corrélation entre espèces anciennes et espèces nouvelles et non sur un nombre d'espèces absolu.

**Comment by lpofredc** [comment]
Changement de position, on compare un nb d'espèces absolu.
