### ISSUE TITLE
Identification des anciens points EPOC

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#120]
ℹ️ À récupérer avec l'API FF grâce au code étude EPOC
⚠️ **Taguer les points EPOC 2019-2020** avec le code étude EPOC directement dans FF via l'API

**Comment by lpofredc** [comment]
Travail d'analyse préliminaire à mener d'après le tableau fourni par la LPO France
* Mettre à jour les données depuis FF pour rapatrier les `project_code` depuis l'ouverture récente du droit correspondant
* Comparer les codes études des données correspondantes dans FF avec les données fournies.
* Si pas de pb, lancer un update par API des données FF
* Remettre à jour les données depuis FF.

**Comment by lpojgc** [comment]
choix avec JD de ne pas intégrer ces EPOC
