### ISSUE TITLE
API liste des espèces par maille : ajouter le calendrier d'observation de l'espèce

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#121]
💡 API concernée : `/api/v1/area/taxa_list/{id_area}`

ℹ️ Le calendrier est présenté de cette manière : 
![calendrier_espèce](https://user-images.githubusercontent.com/57666163/129741539-74cf11d2-ddc7-4715-a54e-b13609a42d08.png)

**Comment by lpofredc** [comment]
Renvoyer dans l'API un array listant les mois de présence. ex: `[1,2,3,9,10,11]`
