### ISSUE TITLE
Infobulle sur "espèces hivernantes" indiquant la période d'hivernage

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#134]
Afficher infobulle précisant les périodes "d'hiver"

**Comment by lpofredc** [comment]
@lpojgc , des précisions ? ou on ferme.

**Comment by lpojgc** [comment]
ça devait être de préciser les périodes pour l'hiver mais ça rejoint la question de la page de méthode à rédiger
