### ISSUE TITLE
API tableau des espèces contactées pour la maille cliquée - REPRO

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#14]
:bird: Repro = données avec code atlas
:warning: Ne pas tenir compte des espèces sensibles !

:information_source: Colonnes du tableau (données **à la maille**) : 

- cd_nom taxref
- Nom scientifique taxref
- Nom vernaculaire taxref
- L'espèce est contactée sur la période actuelle (true/false)
- L'espèce a été contactée anciennement (true/false)
- Dernière année de contact

**Comment by lpofredc** [comment]
suite #33
