### ISSUE TITLE
espèce disponible dans la liste mais pas de donéne dans le territoire

### ISSUE THREAD

**Issue by ClemLPO** [lpoaura/BirdAtlasOfFrance#148]
si on choisi l'espèce Rougequeue de Moussier dans la liste pour voir la carte on a ce message à droite : "Pas de données pour la saison et l'emprise choisies"

il ne faudrait donc pas qu'il soit proposé dans la liste des espèces.

**Comment by lpofredc** [comment]
Situation délicate à gérer, il existe une "acceptée" donnée (https://www.faune-france.org/index.php?m_id=54&id=32608521), de 2013 et une donnée protégée de 2020 à soumettre au CHN (https://www.faune-france.org/index.php?m_id=54&id=91129900)

**Comment by lpojgc** [comment]
cas marginal, non ? on clôture
