### ISSUE TITLE
Internal Server Error sur interrogation taxa

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#156]
Bonjour,
Lorsque j'interroge l'api pour la Mouette rieuse : https://www.oiseauxdefrance.org/api/v1/taxa/530157?period=breeding_old&envelope=-13,43,9,50
j'ai une réponse "Internal Server Error".
Marc
PS : l'envoi via "À propos/Contact/J'aimerais vous faire part de retours sur le site" répond "L'envoi du mail a échoué... "

**Comment by mgageo** [comment]
Toujours cette erreur le 25/11/2021

**Comment by lpofredc** [comment]
Corrigé, l'API VisioNature renvoie les codes atlas VisioNature, et non les codes EBCC.
https://wiki.biolovision.net/Correspondance_codes_atlas
