### ISSUE TITLE
API tableau de bord pour la maille cliquée

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#16]
:information_source: Données nécessaires **à la maille** : 
- [x] Dernière actualisation
- [x] Complétude de prospection de la maille (%)
- [x] Nb de données
- [x] Nb d'espèces nicheuses / Nb d'espèces hiver / Nb d'espèces toutes saisons
- [x] Nb de données par mois (répartition temporelle des données)
- [x] Durée de prospection (en heures) : 
    - [x] Pour la période de repro
    - [x] Pour la période d'hivernage 
- [ ] ~~Nb de points EPOC~~

**Comment by lpofredc** [comment]
Pour les epocs, cf. #19.

**Comment by eguilley** [comment]
L'API `/api/v1/area/general_stats/{id_area}` renvoie une erreur 500

**Comment by eguilley** [comment]
### Répartition temporelle des données
@lpofredc Certaines mailles (`/api/v1/area/time_distrib/661699/month`) ne présentent aucune donnée pour certains mois. Au lieu de ne rien renvoyer pour les mois concernés (cela provoque un bug sur l'affichage de l'histogramme), j'aurais besoin de la valeur 0, comme suit :
```
[
  {
    "label": 1,
    "count_data": 0
  },
  ...
]
```

**Comment by lpofredc** [comment]
Complexe au regard de la généricité de la fonction qui éxécute une requête côté BDD avec les fonctions natives d'extraction de dates et ne retourne que périodes avec données. Privilégier une attribution des données côté frontend avec une itération sur les lables: index du label dans l'array + 1 = label de l'API.

**Comment by lpofredc** [comment]
ex: 
```javascript
const months = [
      'Jan',
      'Fév',
      'Mars',
      'Avril',
      'Mai',
      'Juin',
      'Juil',
      'Août',
      'Sept',
      'Oct',
      'Nov',
      'Déc',
    ]

const data = [{
  label: 3,
    value: 5
},{
label:6,
value:10
}]

 const values = months.map((e,i) => data.find(de => de.label==i+1)?.value || 0  )
```

**Comment by eguilley** [comment]
Merci, c'est corrigé !

**Comment by lpofredc** [comment]
fix in 616e9f4f26c97e17c98c1d92bedc3623c7831da9

**Comment by eguilley** [comment]
Je me demande s'il n'y a pas toujours un problème avec `data_count`...

Exemple de la maille **E100N656** qui ne présente aucune espèce après 2019. Pourtant l'API `/api/v1/area/general_stats/50061` renvoie les données suivantes : 
```
{
  "last_date": "2015-08-20",
  "data_count": 22,
  "taxa_count_all_period": 0,
  "taxa_count_wintering": 0,
  "taxa_count_breeding": 0,
  "prospecting_hours_other_period": 0,
  "prospecting_hours_wintering": 0,
  "prospecting_hours_breeding": 0
}
```
avec un `data_count` qui n'est pas égal à 0. C'est normal @lpofredc ?

**Comment by lpofredc** [comment]
MaJ non appliqué sur ma bdd, corrigé
