### ISSUE TITLE
Graphique phénologie reproduction

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#165]
![phenology_breeding](https://user-images.githubusercontent.com/57666163/150322491-bc97b95e-bb77-4736-8da6-a3227f35d88a.png)

Prévoir les graphiques de phénologie.

:warning: Attention pour les API :

- Il y a aura un code pour la première courbe et un autre pour la seconde

- Les codes vont varier en fonction des espèces

=> **Production d'une table avec cd_nom/code_début/code_fin**

**Comment by lpofredc** [comment]
Attente: 

> Axe des abscisses: décade (36 décades dans une année)​
> Axe des ordonnées: nombre de données​
> (possibilité de les avoir en %age pour éviter d’avoir une différence d’échelle trop importante entre les deux histogrammes)​
> Le premier histo correspond aux données avec code atlas « mâles chanteur », marqueur du début de la reproduction​
> Le second histo correspond aux données avec code atlas « jeunes » marqueur de la fin de la reproduction.​

![image](https://user-images.githubusercontent.com/22891423/141130775-5f0a65cd-0d9b-4b35-b6f1-a2a293769e41.png)

**Comment by lpojgc** [comment]
définir profil par défaut et compléter une table pour les cas spécifiques

**Comment by lpofredc** [comment]
Les décades sont à définir sur le principe qu'un mois couvre 3 décades:

- décade 1 : janvier du 1 au 10
- décade 2 : janvier du 11 au 20
- décade 3 : janvier > 21
- décade 4 : février du 1 au 10
- ...

Pour simplifier les requêtes, une table de correspondance sera créée avec les colonnes:

- mois
- jour du mois
- numéro de décade

**Comment by lpojgc** [comment]
On part sur le principe général suivant :

- première courbe : male chanteur
- seconde courbe : code 12, jeune à l'envol

On fait une table pour les exceptions, qui sera peuplée à la main. A priori pas besoin de la territorialisée, mais si pas trop lourd le prévoir pour anticiper d'éventuels changements ?

**Comment by eguilley** [comment]
@lpofredc voilà comment j'ai construit les données pour d3.js : 
```
dataPhenologyBreeding: {
      label: 'Nombre de données',
      atlasCodes: ['Mâle chanteur', 'Jeunes'],
      data: [
        { label: 'D1', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D2', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D3', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D4', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D5', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D6', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D7', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D8', firstAtlasCode: 10, secondAtlasCode: 0 },
        { label: 'D9', firstAtlasCode: 20, secondAtlasCode: 0 },
        { label: 'D10', firstAtlasCode: 30, secondAtlasCode: 0 },
        { label: 'D11', firstAtlasCode: 40, secondAtlasCode: 0 },
        { label: 'D12', firstAtlasCode: 50, secondAtlasCode: 0 },
        { label: 'D13', firstAtlasCode: 60, secondAtlasCode: 0 },
        { label: 'D14', firstAtlasCode: 70, secondAtlasCode: 0 },
        { label: 'D15', firstAtlasCode: 90, secondAtlasCode: 0 },
        { label: 'D16', firstAtlasCode: 120, secondAtlasCode: 10 },
        { label: 'D17', firstAtlasCode: 250, secondAtlasCode: 20 },
        { label: 'D18', firstAtlasCode: 370, secondAtlasCode: 40 },
        { label: 'D19', firstAtlasCode: 550, secondAtlasCode: 50 },
        { label: 'D20', firstAtlasCode: 360, secondAtlasCode: 70 },
        { label: 'D21', firstAtlasCode: 290, secondAtlasCode: 90 },
        { label: 'D22', firstAtlasCode: 270, secondAtlasCode: 95 },
        { label: 'D23', firstAtlasCode: 200, secondAtlasCode: 140 },
        { label: 'D24', firstAtlasCode: 150, secondAtlasCode: 170 },
        { label: 'D25', firstAtlasCode: 90, secondAtlasCode: 150 },
        { label: 'D26', firstAtlasCode: 55, secondAtlasCode: 130 },
        { label: 'D27', firstAtlasCode: 40, secondAtlasCode: 100 },
        { label: 'D28', firstAtlasCode: 15, secondAtlasCode: 90 },
        { label: 'D29', firstAtlasCode: 0, secondAtlasCode: 80 },
        { label: 'D30', firstAtlasCode: 0, secondAtlasCode: 70 },
        { label: 'D31', firstAtlasCode: 0, secondAtlasCode: 50 },
        { label: 'D32', firstAtlasCode: 0, secondAtlasCode: 20 },
        { label: 'D33', firstAtlasCode: 0, secondAtlasCode: 10 },
        { label: 'D34', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D35', firstAtlasCode: 0, secondAtlasCode: 0 },
        { label: 'D36', firstAtlasCode: 0, secondAtlasCode: 0 },
      ],
      colors: ['#435EF2', '#E56B6F'],
    }
```
