### ISSUE TITLE
Carte de prospection : Fou de Bassan en période de reproduction

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#168]
J'ai des gros doutes pour cette espèce en Bretagne.
 
![image](https://user-images.githubusercontent.com/2681495/141163960-80a6ffe7-88f3-421d-bd1e-70d10bb2eb56.png)

De plus la donnée en Bretagne sud est en cours de vérification.

**Comment by mgageo** [comment]
Je viens de voir de la barge à queue noire dans les mailles [E015N686](https://www.faune-bretagne.org/index.php?m_id=94&p_c=4&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.01.2019&sp_DTo=11.11.2021&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=225&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=0010&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E015N686&sp_Grid=42&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-5&sp_AltitudeTo=387&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e__S0&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_I=0&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=1&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=11.11.2021&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher)  et [E022N675](https://www.faune-bretagne.org/index.php?m_id=94&p_c=4&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.01.2019&sp_DTo=11.11.2021&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=225&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=0010&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E022N675&sp_Grid=117&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-5&sp_AltitudeTo=387&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e__S0&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_I=0&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=1&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=11.11.2021&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) je n'ai pas trouvé dans faune-bretagne

**Comment by lpofredc** [comment]
Merci @mgageo  pour ces vérifications attentives. Comme évoqué précédemment, il s'agit pour partie de pb de synchronisation entre FF et la base de données. Un nouvel import s'appuyant sur de nouvelles versions du client de synchronisation ([lpo/Client-API-VN](https://framagit.org/lpo/Client_API_VN/)) et des scripts de mise à jour de GeoNature ([lpoaura/gn_vn2synthese](https://github.com/lpoaura/gn_vn2synthese)) est en cours de finalisation et devrait résoudre ces pb.

En l'état actuel, au regarde du dispositif de synchronisation quotidienne (mise à jour des données VisioNature toutes les heures et des données ODF toutes les 6h), toute donnée non vérifiée sera affichée sur ODF.

Pour le Fou de Bassan, la donnée de Saint-Malo est une donnée qui avait un code atlas (2) retiré par la suite (dernière mise à jour le 28/09 > https://www.faune-bretagne.org/index.php?m_id=54&uid=65_106369597

l'obs sur les moutons est en cours de vérif depuis le 04/10 > https://www.faune-bretagne.org/index.php?m_id=54&uid=65_107657238

Concernant la Barge à queue noire. les données existent bien sur FF mais sont en cours de vérif depuis peu (4/10):
https://www.faune-bretagne.org/index.php?m_id=54&uid=46_4678719
![image](https://user-images.githubusercontent.com/22891423/141757059-559a9709-9ba7-4424-89f6-d95f23532568.png)

https://www.faune-bretagne.org/index.php?m_id=54&uid=65_104935878
![image](https://user-images.githubusercontent.com/22891423/141757752-7e977939-c8de-4888-9939-4d08c0760d15.png)

**Les données en cours de vérification, si bien à jours dans la base de données, sont exclues d'ODF.**

Dans [lpoaura/gn_vn2synthese](https://github.com/lpoaura/gn_vn2synthese)
https://github.com/lpoaura/gn_vn2synthese/blob/6d21c1c1610a0d397d882991b8203e545cb49648/08_upsert_observations.sql#L206-L217

Dans ODF:
https://github.com/lpoaura/BirdAtlasOfFrance/blob/497d3e578049a8af37b42832a0fa441f50edf141/data/sql_scripts/01_data_for_atlas.sql#L63-L64

**Comment by lpofredc** [comment]
La plateforme est maintenant à jour !
![Capture d’écran 2021-11-15 à 16 24 02](https://user-images.githubusercontent.com/22891423/141807784-2dee8ed4-c2ce-4c7b-8501-484a80f16cd9.png)
![Capture d’écran 2021-11-15 à 16 24 40](https://user-images.githubusercontent.com/22891423/141807887-b2fa7509-faad-4bd9-8ac1-838598121490.png)
