### ISSUE TITLE
Script data/sql_scripts/01_data_for_atlas.sql : questions

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#169]
Dans ce script, le filtrage des données par date me semble comporter des erreurs.

Le 01/01/2019 est affecté en old_data_breeding au lieu de new_data_breeding.

Pour new_data_all_period, le choix du 31/01/2019 comme début de période exclu les données de nidification de janvier 2019.

**Comment by lpofredc** [comment]
En effet ;), une petite coquille. le 01/01/2019 doit bien être attribué à `new_data_breeding`.

Bien vu pour `new_data_all_period`, c'est en effet incohérent avec les autres dates. nous allons corriger.
