### ISSUE TITLE
Espèces régionales

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#170]
Dans faune-bretagne la configuration des espèces a été complétée.
Comment sont traitées ces espèces dans odf ?

|espece                                             |  nb|  
|:--------------------------------------------------|---:|  
|Bergeronnette centratlantique (Mf.flava x iberiae) |   4|  
|Bergeronnette de la Manche (M.f.flava x flavissima |   3|  
|Bergeronnette de Yarrell                           |   6|  
|Bergeronnette grise (M.a.alba)                     | 171|  
|Bergeronnette printanière (M.f.flava)              |  15|  
|Canard hybride                                     |   1|  
|Effraie des clochers (T.a.alba)                    |   9|  
|Goéland argenté (L.a.argenteus)                    |  18|  
|Goéland brun (L.f.graellsii)                       |  11|  
|Gorgebleue de Nantes (L.s.namnetum)                |   3|  
|Gravelot indéterminé                               |   1|  
|Oie cendrée férale                                 |   5|  
|Oie indéterminée                                   |   1|  
|Pipit maritime (A.p.petrosus)                      |   5|  
|Pouillot véloce (P.c.collybita)                    |   1|

**Comment by lpofredc** [comment]
Pour la France métropolitaine, ODF s'appuie Faune-France et donc les espèces telles que configurées dans Faune-France. A titre d'exemple, la Bergeronnette de Yarell est encore une sous-espèce de _M. alba_. De plus, l'instance est installé avec un TaxRef en version 13 (ou la Bergeronnette de Yarell en tant qu'espèce n'est encore inscrite).

ODF utilise les données d'espèces et sous-espèces "vraies" (pas de _sp._). Les sous-espèces sont toutes agrégées à l'espèce et quelques sous-espèces (cf. ci-après) sont toutefois distinguées et consultable indépendamment).

| cd\_nom | lb\_nom | nom\_vern |
| :--- | :--- | :--- |
| 886230 | Acanthis flammea cabaret | Sizerin cabaret |
| 886232 | Acanthis flammea flammea | Sizerin boréal |
| 4505 | Corvus corone cornix | Corneille mantelée |
| 3745 | Motacilla flava flavissima | NULL |
| 886211 | Poecile montanus montanus | Mésange alpestre |

**Comment by mgageo** [comment]
Pour"Motacilla flava flavissima" le texte affiché est  "Bergeronnette flavéole (M.f.flavissima)", "Bergeronnette flavéole" devrait être suffisant ?

**Comment by lpofredc** [comment]
Les noms français, anglais et scientifiques sont issus de Faune-France. Il conviendrait en effet de standardiser sur ODF.

**Comment by mgageo** [comment]
Une donnée de "Effraie des clochers (T.a.alba) (Tyto alba alba)" comme https://www.faune-bretagne.org/index.php?m_id=54&id=2996118 n'est donc pas prise en compte ?

**Comment by lpofredc** [comment]
Pour l'atlas, nous menons un travail de mise en correspondance du référentiel espèces VisioNature avec le référentiel taxonomique TaxRef (référentiel utilisé pour ODF). En effet, Tyto alba alba ne dispose pas actuellement de correspondance. Nous allons corriger cela, merci pour l'info.

**Comment by lpojgc** [comment]
ticket clos, repris dans https://github.com/lpoaura/BirdAtlasOfFrance/issues/332
