### ISSUE TITLE
Données manquantes Chevêche d'Athéna

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#171]
Jérémy : 

> Un observateur a détecté un problème sur des données de Chevêche d'athéna. Dans la maille E043N692, il n'y a pas de données de l'espèce après 2019. Or il y a au moins deux données dans faune-france. Est-ce que vous avez une explication ?

**Comment by eguilley** [comment]
> Il y a une autre donnée de Chevêche le 13/09/2021 dans cette même maille, mais celle-ci a bien été modifiée d'où le problème d'affichage. Pour les deux autres de Dominique Loir (UUID: 27f606ab-374c-41ec-b9ac-041006886fbd et UUID: 0ce9ba5b-361d-41ec-b9ac-04100687a1ce) je ne sais pas s'il les a modifiées.

**Comment by lpofredc** [comment]
Oui, pb de synchro. cf. #168 & #160
