### ISSUE TITLE
API requête area/knowledge_level/ATLAS_GRID

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#172]
Bonjour,
Les données fournies par cette requête (old_count, new_count) correspondent à des nombres d'espèces ?
Si oui il y a un décalage avec les requêtes par maille.
Marc

**Comment by lpofredc** [comment]
Bonjour @mgageo, Pouvez-vous préciser votre question ?

**Comment by lpofredc** [comment]
Bien vu, je creuse le sujet.

**Comment by lpofredc** [comment]
Corrigé
