### ISSUE TITLE
Oiseaux en hiver : données négatives

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#173]
Bonjour,
Les données négatives (nombre précis à 0 et/ou code atlas 99) sont comptabilisées
exemple Cingle plongeur maille E019N685
Marc

**Comment by lpofredc** [comment]
Etrange... Je ne vois pas mention de cette obs dans ODF (https://www.oiseauxdefrance.org/prospecting?area=10kmL93E019N685&type=ATLAS_GRID). Cette donnée (https://www.faune-france.org/index.php?m_id=54&id=98100278) est bien exclue par la règle suivante:

https://github.com/lpoaura/BirdAtlasOfFrance/blob/497d3e578049a8af37b42832a0fa441f50edf141/data/sql_scripts/01_data_for_atlas.sql#L65-L66

Le traitement à la source se fait comme tel (https://github.com/lpoaura/gn_vn2synthese/blob/6d21c1c1610a0d397d882991b8203e545cb49648/08_upsert_observations.sql#L257-L266):

```sql
 SELECT
        CASE
            WHEN ((new.item #>> '{observers,0,count}' = '0'
                AND new.item #>> '{observers,0,estimation_code}' LIKE 'EXACT_VALUE') OR
                  (new.item #>> '{observers,0,atlas_code}' = '99')) THEN
                ref_nomenclatures.get_id_nomenclature('STATUT_OBS', 'No')
            ELSE
                ref_nomenclatures.get_id_nomenclature('STATUT_OBS', 'Pr')
            END
        INTO the_id_nomenclature_observation_status;
```

**Comment by mgageo** [comment]
La donnée n'est plus présente le 25/11/2021
