### ISSUE TITLE
Oiseaux en hiver : données avec indice de nidification

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#175]
La donnée de sittelle torchepot avec indice 3 ( https://www.faune-bretagne.org/index.php?m_id=54&id=4061659 ) n'est pas prise en compte dans odf maille E016N685.
Il existe une règle pour exclure ces données ?

**Comment by lpofredc** [comment]
? Qu'entendez vous par pas prise en compte. On retrouve bien cette espèce en nicheur possible sur cette maille et la donnée est bien utilisée 

```
┌─[ RECORD 1 ]────────┬────────────┐
│ id_area             │ 43107      │
│ id_form_universal   │ 65_1292737 │
│ id_data             │ 8921043    │
│ cd_nom              │ 3774       │
│ date_min            │ 2021-01-29 │
│ new_data_all_period │ t          │
│ old_data_all_period │ f          │
│ old_data_wintering  │ f          │
│ new_data_wintering  │ f          │
│ old_data_breeding   │ f          │
│ new_data_breeding   │ t          │
│ bird_breed_code     │ 3          │
└─────────────────────┴────────────┘
```

![Screenshot 2021-11-17 at 21-22-51 Atlas des Oiseaux de France](https://user-images.githubusercontent.com/22891423/142276748-4316ee6e-3980-4f92-9607-65eb46789521.png)

**Comment by lpofredc** [comment]
Et oui, en effet, une donnée avec indice de repro n'est plus considérée hivernante.

**Comment by lpojgc** [comment]
Je n'avais pas en tête ce qu'il se passait mais les données "en hiver" (et non hivernantes) devraient être toutes les données de décembre et janvier.

Par conséquent une donnée en décembre ou janvier avec indice de repro devrait être prise en compte pour les périodes "hiver" et "repro"...

**Comment by mgageo** [comment]
Merci pour la remarque "en hiver", c'est un combat que je mène aussi au niveau local.
Il ne doit y avoir que les anciens qui ont participé à des atlas hivernants avec les 2 passages.

**Comment by lpofredc** [comment]
C'est corrigé. J'ai commencé à rédiger une documentation sur ces sujets.

https://birdatlasoffrance.readthedocs.io/en/latest/docs/data/

source dans le dépot https://github.com/lpoaura/BirdAtlasOfFrance/tree/dev/docs
