### ISSUE TITLE
Oiseaux en hiver : donnée du 31 janvier 2021

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#177]
Une donnée de "Pinson du Nord" ( https://www.faune-bretagne.org/index.php?m_id=54&id=4076324 )  pour la maille E038N678 ne figure pas sur le site https://www.oiseauxdefrance.org/prospecting/?area=10kmL93E038N678&type=ATLAS_GRID

Sur l'appel de cette dernière url les informations n'apparaissent qu'après avoir dezoomé si la consultation s'effectue dans une nouvelle fenêtre du navigateur.

**Comment by lpofredc** [comment]
Cette donnée n'existe pas sur [FF](https://www.faune-france.org/index.php?m_id=94&p_c=3&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=31.01.2021&sp_DTo=31.01.2021&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=Fringilla+&sp_S=519&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Family=1&sp_PChoice=canton&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=1&sp_CommuneCounty=7&sp_Commune=2222&sp_Info=&sp_P=0&sp_Grid_Info=&sp_Grid=0&sp_Polygon=&sp_PolygonSaveName=&zip_shapefile=&input_epsg=4326&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_EntityE=0&sp_OnlyAH=0&sp_Ats=-00000&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=180&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=21.11.2021&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher)...

![Screenshot 2021-11-21 at 21-46-36 Résultat de la recherche - www faune-france org](https://user-images.githubusercontent.com/22891423/142778399-c97ff475-6928-4850-a02b-5a018af423f0.png)

**Comment by mgageo** [comment]
J'ai sollicité Gaëtan sur une autre donnée, la réponse 
Bonsoir,  
Nous n’avons pas terminé la consolidation de toutes les données dans Faune-France.  
Il y a encore des cas qu’on doit retraiter. C’est probablement une des données concernées (en fait toute la liste est manquante).  
On devrait être bon dans quelques semaines.  
Merci,  
Gaëtan
