### ISSUE TITLE
Oiseaux nicheurs : données absentes

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#178]
L'observation de "Grèbe huppé" https://www.faune-bretagne.org/index.php?m_id=54&id=2656983 avec indice 18 ne figure pas dans odf maille E018N685

**Comment by lpofredc** [comment]
En effet, le pb vient a priori de la donnée. Sur FF, la donnée est à plus de 20km du lieu-dit du formulaire. Le lieu dit est bien sur la maille E018N685, la donnée est sur la maille E018N686 et elle est bien prise en compte sur ODF (https://www.oiseauxdefrance.org/prospecting?area=10kmL93E018N686&type=ATLAS_GRID)

https://www.faune-france.org/index.php?m_id=54&uid=65_80152271
![Screenshot 2021-11-21 at 21-40-47 Détail de l'observation - www faune-france org](https://user-images.githubusercontent.com/22891423/142778213-eb077c37-ae39-4561-960d-9ac4797ff71f.png)

**Comment by mgageo** [comment]
Si je comprends bien la différence est sur la maille attribuée : E018N685 avec les coordonnées du lieudit du formulaire, E018N686 avec les coordonnées de l'observation.
Je détermine la maille à partir des coordonnées présentes dans la donnée récupérée avec l'api vn, je croyais que ces coordonnées étaient celles de l'observation et non celles du lieudit, je me trompe ?

**Comment by lpofredc** [comment]
C'est à confirmer du côté BioloVision. Pour l'atlas, le rattachement géographique des observations est réalisé à partir des coordonnées de l'observation. Il est possibles que dans faune-france, le rattachement des observations soit effectué via le lieu-dit attribué à l'observation.
