### ISSUE TITLE
Oiseaux nicheurs : indice trop élevé

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#179]
Pour l'accenteur mouchet sur sur la maille E023N684, l'indice le plus élevé dans [faune-bretagne](https://www.faune-bretagne.org/index.php?m_id=94&p_c=4&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.01.2019&sp_DTo=18.11.2021&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=461&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=0010&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E023N684&sp_Grid=145&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-5&sp_AltitudeTo=387&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e__S0&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_I=0&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=1&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=18.11.2021&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) est 3.
Dans odf l'espèce est en certain.

**Comment by lpofredc** [comment]
Etrange, Peut-être un pb de synchro entre FF et FB, j'ai cette donnée sur FF:
https://www.faune-france.org/index.php?m_id=54&id=104940442

**Comment by mgageo** [comment]
Et je trouve pas cette donnée dans faune-bretagne
![image](https://user-images.githubusercontent.com/2681495/142870985-2ea38e90-2801-4c76-be49-f29a3c292751.png)

![image](https://user-images.githubusercontent.com/2681495/142871296-a21833dc-5142-4d84-b62f-14c97ee9ce20.png)

cela ressemble effectivement à un problème de synchro entre FB et FF

**Comment by mgageo** [comment]
Attente correction synchronisation des faunes
