### ISSUE TITLE
Données manquantes

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#183]
Jérémy : 

> À partir de l'export de la base que j'ai effectué il y a quelques jours (mv_area_knowledge_list_taxa), j'ai repéré des incohérences. Par exemple, pour la maille **E009N684**, il y a des espèces qui sont notées en hivernage mais dont la dernière année d'observation est vierge. Et il y a la Bécassine des marais qui est donnée comme hivernante avant 2019, mais pas après 2019, alors qu'il y a une donnée le 02/01/2019.

**Comment by eguilley** [comment]
Sur la maille E009N684 ? Un exemple d'espèce pour laquelle ça ne fonctionne pas ?

**Comment by lpojgc** [comment]
le pb a été réglé à la dernière mise à jour
