### ISSUE TITLE
Incohérences dans la VM atlas.mv_area_knowledge_list_taxa

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#185]
Dans la VM `atlas.mv_area_knowledge_list_taxa`, il y a de nombreuses lignes pour lesquelles `wintering_count_data_old` et `wintering_count_data_new` valent 0 (donc aucune donnée observée en hiver en théorie) et pourtant `wintering_last_obs` n'est pas NULL. Exemple de la ligne id_area=67289 et cd_nom=441667. Pareil pour la repro.

Il y a aussi le cas contraire : 1 donnée dans `wintering_count_data_old` et pourtant `wintering_last_obs` est NULL. Exemple de la ligne id_area=42510 et cd_nom=998.

C'est normal ?

**Comment by lpofredc** [comment]
En effet, un coquille dans la requête...

https://github.com/lpoaura/BirdAtlasOfFrance/blob/02a450758ca90baeb04913ef70701f2860dd684b/data/sql_scripts/03_area_knowledge_list_taxa.sql#L80-L81

**Comment by eguilley** [comment]
Ça a été corrigé ça @lpofredc ?

**Comment by lpofredc** [comment]
Corrigé dans la PR #194
