### ISSUE TITLE
API chiffres-clés de l'Atlas

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#19]
:information_source: Données nécessaires **à l'échelle de l'Atlas** et pour **toutes saisons** : 

- [ ] ~~Nb de données (sur période atlas)~~
- [ ] ~~Nb d'observateurs  (sur période atlas)~~
- [x] Nb espèces nicheuses / Nb espèces hiver / Nb espèces toutes saisons  (sur période atlas)
- [ ] ~~Indicateur de complétude de l’Atlas : pourcentage de mailles pour lesquelles la complétude de prospection est supérieure à 90% (par exemple), c’est-à-dire pour lesquelles la liste d’espèces contactées est quasi complète.~~
- [ ] ~~Nb de points EPOC~~
- [x] Durée de prospection totale (en heures) : 
  - [x] Pour la période de repro
  - [x] Pour la période d'hivernage
  - [x] Pour la période intermédiaire

**Comment by lpofredc** [comment]
- Points EPOC, données formulaires d'une durée de 5 minutes avec localisation précise des oiseaux. (i.e. localisation différente de l'observateur).
- EPOC Atlas, identifiables via code étude (à venir, pas encore en place).

**Comment by lpofredc** [comment]
Partially donne un #47

**Comment by lpojgc** [comment]
Remplacer le nombre d'heures  totales de prospection par le nombre d'heures "Autres périodes".

**Comment by eguilley** [comment]
L'API renvoie une erreur 500
