### ISSUE TITLE
Détails du nombre d'espèces en page d'accueil

### ISSUE THREAD

**Issue by A-d-r-i** [lpoaura/BirdAtlasOfFrance#192]
Bonjour,
Les chiffres paraissent étonnamment importants sur la page d'accueil (je suis étonné que la France métropolitaine accueille 800 espèces nicheuses et 850 hivernantes ! 😇 ). Ces chiffres tiennent-ils compte des espèces d'Outre-Mer sachant qu'elles ne sont pas encore disponible à la recherche ?
![image](https://user-images.githubusercontent.com/27277698/145770876-5ffc3ed6-b4b9-4926-8fe7-ee592000087a.png)

Merci pour vos infos !

**Comment by lpofredc** [comment]
Bonjour @A-d-r-i , en effet, ces chiffres comprennent également les données de [faune-guyane](https://www.faune-guyane.fr/), actuellement en cours d'intégration.

**Comment by A-d-r-i** [comment]
Parfait ! Merci pour la réponse 😊
