### ISSUE TITLE
Intégration des données d'enquêtes

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#195]
Créer les CA et JDD suivants :
|**Cadre acquisition**|**JDD**|
|---|---|
|Suivi milan royal|Comptage des dortoirs hivernaux (données de terrain)|
|Suivi vautour percnoptère|Suivi de reproduction (données de terrain)|
|Synthèse des données de reproduction|Données synthétiques de reproduction (données biblio)|

Limite le nombre d'information renseignées dans les CA et JDD

**Comment by afourneyron** [comment]
Tableau à fournir pour faire l'ensemble des jeux de données, par fichiers.
Puis demande comment sont imbriqué les JDD dans les CA
Puis informations complémentaires des JDD et CA.

Tableau fourni une fois l'ensemble des JDD intégrés
