### ISSUE TITLE
Gestion et définition des types de graphiques

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#196]
Type de graphiques :

- all_seasons_phenology (d'après données FF)
- migration_phenology (d'après données FF)
- altitudinal_all_season_phenology (d'après données FF)
- breeding_phenology (d'après données FF)
- stoc_trend (données fournies LPO France)
- breed_mediane_ic (mediane + intervalle de confiance) (données fournies LPO France)
- breed_min_max (données fournies LPO France)
- breed_count (données fournies LPO France)
- altitudinal_breeding_phenology (données fournies LPO France)
- winter_trend (données fournies LPO France)
- winter_mediane_ic (mediane + intervalle de confiance) (données fournies LPO France)
- winter_min_max (données fournies LPO France)
- winter_count (données fournies LPO France)
- altitudinal_winter_phenology (données fournies LPO France)

Il reste probablement des types à ajouter d'autres à modifier.
Actuellement on part du principe que pour une représentation donnée correspond à un seul stype. C'est l'unité et autres champs renseignés dasn la table `info graphe` qui complète les infos du graphiques.

**Comment by lpojgc** [comment]
table `t_representation` à reprendre avec les informations suivantes :
- cd_nom
- période (selon la typologie)
- type de representation (graphique ou carte)
- type de graphique (breed_min_max etc.)
- id_jdd
- titre du graphique

**Comment by lpojgc** [comment]
@lpofredc je te laisse reprendre pour éclater en 2 tables, comme proposé pour limiter la redondance

**Comment by lpofredc** [comment]
Processus d'appel des données par ODF:

1. Pour une espèce, lister les représentations de suivis disponibles  (graphiques et cartes) sur la base des filtres suivants:
  - espèce
  - territoire (France métropolitaine, etc.)
  - période phénologique
2. Récupérer les données à représenter pour chaque représentation disponibles (selon résultat du point 1).

**Comment by lpofredc** [comment]
Au regard de l'hétérogénéité des sources et représentation des données (certains générées depuis les données visionature, d'autres issues de données aggrégées, etc.). Plusieurs API ont été générées. Les graphiques sont générés côté front en fonction des réponses d'API réalisés pour chacun (si pas de données, pas de graphique, si données, graphique).
