### ISSUE TITLE
Affichage milliers graphique tableau de bord

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#197]
Actuellement il y a une virgule comme séparateur des milliers, ce n'est pas une pratique française, Il faudrait la remplacer par un espace insécable.
 ![Screenshot_20211218-073356_Fennec.png](https://user-images.githubusercontent.com/51160496/146632457-cbfbe448-735f-45a8-8794-6fb6fba51f17.png)

**Comment by lpofredc** [comment]
cf. https://github.com/d3/d3/blob/2deab02977e977529823445c9b1b93589cb3e4a8/API.md#number-formats-d3-format

**Comment by eguilley** [comment]
```
const formatter = d3.formatLocale({
  decimal: '.',
  thousands: ' ',
  grouping: [3],
  currency: ['', ''],
}).format(',.0f')

d3.select(this.$el)
  .select('.yAxis')
  .call(d3.axisLeft(yAxis).tickFormat(formatter))
  .selectAll('text')
  .attr(
    'style',
    "font-family: 'Poppins', sans-serif; font-style: normal; font-weight: 300; font-size: 11px; line-height: 12px; color: #000;"
  )
```
