### ISSUE TITLE
Liste des espèces vues avant 2019 : allongement anormal en Bretagne

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#198]
On me signale que de nouvelles espèces improbables (avocette, spatule, chevalier arlequin...) sur des mailles intérieures (par exemple maille [E027N675](https://www.oiseauxdefrance.org/prospecting?area=10kmL93E027N675&type=ATLAS_GRID) ) apparaissent pour les données antérieures à 2019.
Ces données ne figuraient pas dans faune-bretagne.
Avez-vous une idée de l'origine ?

**Comment by lpojgc** [comment]
Merci pour ce retour. A relier avec un retour de JD vendredi que je n'ai pas eu le temps de creuser ?
- un certain nombre d'espèces se sont ajouter dans la liste des espèces Avant 2019, mais je n'arrive pas à retrouver de trace dans les données faune-france ou AOFM. Par exemple, dans la maille E039N654, le Bécasseau violet est donné comme présent mais je ne le retrouve pas
- pour certaines espèces dans la liste, on ne peut pas cliquer dessus pour avoir le résumé des observations, même exemple avec le bécasseau violet, mais aussi sanderling, ara bleu etc.

**Comment by mgageo** [comment]
Est-il possible d'avoir un retour sur les investigations en cours ? ça ouine dans les chaumières bretonnes.

**Comment by lpofredc** [comment]
Bonjour @mgageo,

C'est une erreur de manip en bdd lié à la réintégration des données de l'atlas précédent. Les données associées à une maille l'étaient aussi à leur maille voisine (à cause de la fonction postgis st_intersects()). C'est en cours de correction. 

Merci.

**Comment by mgageo** [comment]
Mélanger deux sources de données est généralement une très mauvaise idée en informatique.

Ce sont les données de l'atlas des oiseaux en hiver de 2009-2010 à 2012-2013 ? cet atlas était déjà en Lambert 93, pourquoi de l'intersects ?
Il me semble qu'il serait préférable de présenter ces données "atlas" dans une colonne séparée dans la vue par maille
![image](https://user-images.githubusercontent.com/2681495/146938522-be66cb7f-f41e-4692-a252-3c3e01538783.png)

**Comment by lpofredc** [comment]
Ces données sont intégrées dans la synthese GeoNature de l'instance dédiée à ODF pour être traitées comme le reste des données. Les données sont en effet déjà compilées à la maille 10x10 officielle lambert93 (la même que ODF).

L'intersecte sert à peupler la table des croisements géographiques (rattachement des données aux différents zonages de l'atlas, territoires couverts notamment qui servent à traiter les espèces distinctement selon leur zone géographique). Le pb est contourné par l'utilisation de la fonction st_touches qui élimine ces effets de bords.

```sql
        INSERT INTO gn_synthese.cor_area_synthese(id_area, id_synthese)
        SELECT
            id_area
          , id_synthese
            FROM
                gn_synthese.synthese
                    JOIN ref_geo.l_areas a
                         ON public.st_intersects(synthese.the_geom_local, a.geom)
            WHERE
                  a.enable
              AND (st_geometrytype(synthese.the_geom_local) = 'ST_Point' OR
                   NOT public.st_touches(synthese.the_geom_local, a.geom))
              AND id_source IN (SELECT DISTINCT id_source FROM tmp.aofm_2009_2012)
        ON CONFLICT (id_area, id_synthese) DO NOTHING;
```

**Comment by mgageo** [comment]
L'ajout de ces données de l'aofm_2009_2012 pourrait être signalé dans les actualités du site.
Allez-vous rendre accessible ces données de l'aofm ?

**Comment by lpofredc** [comment]
En effet, les données ont été intégrées dès le départ sur la plateforme, suite au constat d'un jeu de donnée source erroné, elles ont été supprimées cette automne pour être réintégrées. 

Pb corrigé.
