### ISSUE TITLE
Modification de la phénologie suite à l'intégration de l'aofm

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#202]
Je viens de constater que la "phenology" avait changé entre une version de fin novembre et la version de cet après-midi.

Sur la maille "id_area": 42599, je l'ai sur plusieurs espèces :
"Accenteur mouchet", "Aigle botté", "Aigrette garzette", "Alouette calandrelle", "Alouette des champs", "Avocette élégante", "Bécasseau minute" ...

**Comment by lpofredc** [comment]
@mgageo, pouvez préciser quelle phénologie est concernée et quelques exemples?

**Comment by mgageo** [comment]
Je joins un fichier avec le début du json pour la maille 42599 pour l'accenteur aux dates du 17/11/2021 et au 05/01/2022.

En phenology, le mois de juin a disparu.

[phenology.txt](https://github.com/lpoaura/BirdAtlasOfFrance/files/7816694/phenology.txt)

**Comment by lpofredc** [comment]
En effet, la phénologie est maintenant uniquement calculée sur les données de la "période" ODF, donc à partir de 2019 tandis que la première version se basait sur toutes les données disponibles en bdd. En ce qui concerne cette maille, cette espèce  n'est en effet [pas présente sur ces dates](https://www.faune-france.org/index.php?m_id=94&p_c=3&p_cc=-1&sp_tg=1&sp_DFrom=06.01.2022&sp_DTo=06.01.2022&sp_DChoice=season&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=6&sp_DSeasonToDay=31&sp_DSeasonToMonth=7&sp_DOffset=5&sp_SChoice=species&speciesFilter=Prunella+mod&sp_S=461&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Family=1&sp_cC=11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111&sp_cCO=0&sp_CommuneCounty=7&sp_Commune=2222&sp_Info=E011N679&sp_PChoice=grid&sp_Grid_Info=E011N679&sp_Grid=4&sp_Polygon=&sp_PolygonSaveName=&zip_shapefile=&input_epsg=4326&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_EntityE=0&sp_OnlyAH=0&sp_Ats=-00000&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=180&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=06.01.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) sur la période ODF.

![image](https://user-images.githubusercontent.com/22891423/148355300-248eb627-8b8f-4fa0-a323-47af091c139d.png)
