### ISSUE TITLE
http 500 sur api/v1/area/taxa_list

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#203]
Bonjour,

Une série de http 500 ce matin 

https://www.oiseauxdefrance.org/api/v1/area/taxa_list/42510

https://www.oiseauxdefrance.org/api/v1/area/taxa_list/43389
...

**Comment by lpofredc** [comment]
Merci bien vu. C'est lie au changement de nom récent de puffins Ardenna gravis/grisea dans faune.

**Comment by mgageo** [comment]
et cela concerne toutes ces urls 
` https://www.oiseauxdefrance.org/api/v1/area/taxa_list/42510 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/43389 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/43047 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/42557 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/43150 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/43108 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/42997 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/42950 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/43758 
 https://www.oiseauxdefrance.org/api/v1/area/taxa_list/43744 `

**Comment by mgageo** [comment]
Je viens d'être relancé (maille E016N686), vous avancez sur la résolution ?
![image](https://user-images.githubusercontent.com/2681495/148184853-91ba47df-6e67-434e-a782-5da0c1e8c414.png)

**Comment by lpofredc** [comment]
Merci pour ce retour, c'est corrigé. Erreurs provoquées par des valeurs nulles (non permises)à dans les noms d'espèces (cas d'espèces nouvelles dans les obs ou renommées). C'est corrigé, il reste à mettre en place une routine pour automatiser ces intégrations.

**Comment by mgageo** [comment]
Merci, c'est ok
