### ISSUE TITLE
Oiseau en hiver présent sur une maille et absent de faune-france

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#204]
Sur la maille https://www.oiseauxdefrance.org/prospecting?area=10kmL93E022N675&type=ATLAS_GRID, l'Oie des moissons est signalée
 alors qu'elle est absente de [faune-france](https://www.faune-france.org/index.php?m_id=94&p_c=3&p_cc=-1&sp_tg=1&sp_DFrom=17.11.2021&sp_DTo=23.12.2021&sp_DChoice=season&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=12&sp_DSeasonToDay=31&sp_DSeasonToMonth=1&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=63&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E022N675&sp_Grid=117&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_OnlyAH=0&sp_Ats=-00000&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=23.12.2021&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher)

**Comment by lpofredc** [comment]
Ok, ce sont plusieurs observations d'oie de la Toundra (Anser fabalis rossicus) qui sont rattachées à l'espèce Oie des moissons (Anser fabalis).

cf. le résultat de la recherche [ici](https://www.faune-france.org/index.php?m_id=94&p_c=4&p_cc=-1&sp_tg=1&sp_DChoice=all&sp_DFrom=05.01.2022&sp_DTo=05.01.2022&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=66&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Family=1&sp_cC=11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111&sp_cCO=0&sp_CommuneCounty=7&sp_Commune=2222&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E022N675&sp_Grid=117&sp_Polygon=&sp_PolygonSaveName=&zip_shapefile=&input_epsg=4326&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_EntityE=0&sp_OnlyAH=0&sp_Ats=-00000&sp_H%5BCHN%5D%5BACCEPTED%5D=1&sp_H%5BCHA%5D%5BACCEPTED%5D=1&sp_H%5BCHD%5D%5BACCEPTED%5D=1&sp_H%5BCHR%5D%5BACCEPTED%5D=1&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=180&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=05.01.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher)

**Comment by mgageo** [comment]
D'accord, il y a une liste des rattachements disponibles dans le github ?

**Comment by lpofredc** [comment]
Je suis justement en train de l'établir.

**Comment by lpojgc** [comment]
oui ça
          fait partie des choses à intégrer à la partie méthode
    Le 05/01/2022 à 15:12, Fred C a écrit :
    
    
      
      Elle est pour le moment disponible ici, il pourra être
        intéressant de l'intégrer à la plateforme pour plus de
        transparence.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you are subscribed to this
        thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/lpoaura/BirdAtlasOfFrance/issues/204#issuecomment-1005719151",
"url": "https://github.com/lpoaura/BirdAtlasOfFrance/issues/204#issuecomment-1005719151",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
