### ISSUE TITLE
Mailles avec beaucoup d'espèces

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#205]
J'ai encore des mailles avec des listes importantes (> 200 espèces)

https://www.oiseauxdefrance.org/prospecting?area=10kmL93E015N677&type=ATLAS_GRID

https://www.oiseauxdefrance.org/prospecting?area=10kmL93E017N677&type=ATLAS_GRID

...

**Comment by lpofredc** [comment]
Sur la période pré-atlas? car sur la période odf, j'ai des résultats comparables sur faune-france.

**E015N677**

![image](https://user-images.githubusercontent.com/22891423/148080306-ce70f0ab-852a-4c57-bc1f-7d039d7c6611.png)

**E017N677**

![image](https://user-images.githubusercontent.com/22891423/148080438-5ce751af-e054-4697-9d5c-feae9e3f3682.png)

**Comment by mgageo** [comment]
Suite au précédent problème j'ai recherché les mailles avec des chiffres très élevés mais je n'ai pas vérifié sur faune-bretagne. Je n'ai pas de droits sur faune-france et sur une recherche sur faune-bretagne on n'a pas directement le nombre d'espèces (il faut exporter le résultat et ...).
Donc les chiffres dans l'odf sont bons et c'est moi qui avait faux.

**Comment by lpofredc** [comment]
Merci, je ferme l'issue
