### ISSUE TITLE
http 504 sur la page d'accueil

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#206]
l'url https://www.oiseauxdefrance.org/api/v1/period_stats ne répond pas, 24/12/2021 13h55

**Comment by lpofredc** [comment]
Merci, nous creusons le sujet pour identifier l'origine du pb. A priori une perte de connexion avec la bdd.
La mise en place du suivi avec sentry (cf. #208) permettra de plus facilement identifier ces pb.

**Comment by eguilley** [comment]
Le problème ne semble plus se produire actuellement
