### ISSUE TITLE
[Méthode] Intégrer la liste des taxons couverts par l'atlas

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/BirdAtlasOfFrance#212]
Dans les évolutions futures de l'atlas, il sera important de préciser la liste des espèces couvertes et exclues de l'atlas ainsi que les regroupements d'espèces (sous-espèces regroupées à l'espèce).

cf. #204 & [liste provisoire](https://github.com/lpofredc/BirdAtlasOfFrance/blob/dev/docs/docs/specie_list.md)

**Comment by mgageo** [comment]
y compris pour les oiseaux allochtones

**Comment by mgageo** [comment]
Certaines espèces figurent plusieurs fois dans "include"

|odf_sci                    |include                                                                                                                                                                       |
|:--------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Acanthis flammea           |Acanthis flammea, Acanthis flammea flammea, Acanthis flammea cabaret                                                                                                          |
|Acanthis flammea cabaret   |Acanthis flammea cabaret                                                                                                                                                      |
|Acanthis flammea flammea   |Acanthis flammea flammea                                                                                                                                                      |
|Anas crecca                |Anas crecca carolinensis, Anas crecca                                                                                                                                         |
|Anas crecca carolinensis   |Anas crecca carolinensis                                                                                                                                                      |
|Columba livia              |Columba livia domestica, Columba livia                                                                                                                                        |
|Columba livia domestica    |Columba livia domestica                                                                                                                                                       |
|Corvus corone              |Corvus corone cornix, Corvus corone                                                                                                                                           |
|Corvus corone cornix       |Corvus corone cornix                                                                                                                                                          |
|Motacilla flava            |Motacilla flava flava, Motacilla flava iberiae, Motacilla flava cinereocapilla, Motacilla flava thunbergi, Motacilla flava beema, Motacilla flava flavissima, Motacilla flava |
|Motacilla flava flavissima |Motacilla flava flavissima                                                                                                                                                    |
|Poecile montanus           |Poecile montanus, Poecile montanus montanus                                                                                                                                   |
|Poecile montanus montanus  |Poecile montanus montanus                                                                                                                                                     |

**Comment by lpofredc** [comment]
Bonjour @mgageo,

Pouvez-vous préciser votre remarque (Certaines espèces figurent plusieurs fois dans "include").

Le niveau espèce regroupe l'espèce et toutes ses sous-espèces et le niveau sous-espèces ne prend en compte que la sous-espèce.

**Comment by mgageo** [comment]
Donc par exemple "Motacilla flava flavissima" figure dans "Motacilla flava flavissima" et "Motacilla flava"

**Comment by lpofredc** [comment]
Oui, c'est normal et volontaire. Le données de M. flava flavissima sont prises en compte pour:
* Les restitutions sur la M. flava (car c'est une sous-espèce de M. flava)
* Les restitutions de M. flava flavissima (car il a été décidé que cette espèces aurait aussi un traitement distinct). 

Ce n'est pas le cas de toutes les sous-espèces mais seulement quelques unes. C'est un point à présenter à éclaircir dans le volet Matériel et méthodes à venir.

**Comment by lpojgc** [comment]
ticket clos, repris dans https://github.com/lpoaura/BirdAtlasOfFrance/issues/332
