### ISSUE TITLE
API : absence de donnée validée chr

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#213]
Sur une requête https://www.oiseauxdefrance.org/api/v1/area/taxa_list/42647 le Pouillot à grands sourcils n'a pas de données
alors qu'une donnée est présente
![image](https://user-images.githubusercontent.com/2681495/149352385-501d371a-b26a-4e34-91a9-208110413fe5.png)

**Comment by lpofredc** [comment]
Le pb est a priori coté VisioNature. J'ai bien cette donnée mais avec le statut CHR "requested". Le changement de statut CHR n'a semble-t-il pas modifié la date de MaJ de la donnée, nécessaire pour récupérer les changements. La donnée a été validée le 22 novembre 2021 hors la date de dernière modif reste le 12 décembre 2020. Peut-être lié à l'origine de la donnée (ornitho.fr)?

**Comment by lpofredc** [comment]
Un message a été envoyé à Biolovision pour des éclaircissements.
