### ISSUE TITLE
erreur 404 sur https://www.oiseauxdefrance.org/prospecting

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#220]
Depuis 15h56 ce 26/01/2022

**Comment by lpofredc** [comment]
Plutôt depuis 16h56... Pb technique. résolu

**Comment by mgageo** [comment]
j'ai un décalage d'une heure, quasiment 5 heures d'arrêt

**Comment by lpofredc** [comment]
Des MaJ sont également en cours ce matin.

**Comment by mgageo** [comment]
Depuis 9h34 et ça continue ...

**Comment by lpofredc** [comment]
En effet, ça y est, tout est rentré en ordre. Le site a été mise à jour.

**Comment by mgageo** [comment]
Ce matin (vendredi 28/01/2022 6h55) le site est toujours en maintenance, la réponse de l'api peut être courte : https://www.oiseauxdefrance.org/api/v1/search_taxa?limit=10000

**Comment by lpofredc** [comment]
Pas de mise en maintenance depuis hier. Par contre cette API URL a évolué avec une nouvelle url:
https://www.oiseauxdefrance.org/api/v1/search/taxa?limit=10000
