### ISSUE TITLE
Monographie : gestion texte et autre

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#221]
Vu avec JD :

-  normalement pas besoin de régionaliser les info "traits de vie" mais pas sur (notamment habitats)
- sur la rédaction, prévoir de régionaliser.

Perso, j'ai du mal à croire que toutes les infos seront régionalisées... Pour le choix,  mesurer la lourdeur de régionaliser a posteriori vs a priori.

**Comment by lpofredc** [comment]
Actuellement, l'on s'appuie sur TaxHub pour générer et alimenter ce contenu, par la [fonctionnalité des attributs](https://taxhub.readthedocs.io/fr/latest/manuel-utilisateur.html#creer-et-gerer-des-themes-et-attributs-personnalises). Cela offre l'avantage d'être éditable en ligne depuis l'application.

Si l'on doit créer un contenu contextualisé (adapté à chaque territoire avec éventuellement un contenu générique par défaut), cela implique de créer une structure spécifique en base de donnée et, en l'état, de peupler ce contenu directement en base de données, ODF n'étant pas disposant pas de backoffice. c'est donc nettement plus lourd en terme de développements et de maintenance.


![Screenshot 2022-02-01 at 16-35-46 TaxHub - Gérer mes taxons](https://user-images.githubusercontent.com/22891423/151999317-2a04c2f6-735d-4c24-af09-3ac076780875.png)

**Comment by lpojgc** [comment]
vu la complexité et l'absence d'info régionalisée, on ne régionalise pas, on verra + tard si le bsoin se fait sentir (et on ne s'adosse plus sur taxhub).
