### ISSUE TITLE
Graphique tendance d'évolution

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#225]
![trend](https://user-images.githubusercontent.com/57666163/152190356-b99638f6-7fac-425d-8001-0a6394eabc6e.png)

**Comment by eguilley** [comment]
@lpofredc voilà comment j'ai construit les données pour d3.js :
```
    dataTrend: {
      trend: {
        label: "Indice d'abondance",
        data: [
          { label: 2006, index: 1.02 },
          { label: 2007, index: 1.09 },
          { label: 2008, index: 1.15 },
          { label: 2009, index: 1.11 },
          { label: 2010, index: 1.01 },
          { label: 2011, index: 0.89 },
          { label: 2012, index: 0.84 },
          { label: 2013, index: 0.81 },
          { label: 2014, index: 0.86 },
          { label: 2015, index: 0.91 },
          { label: 2016, index: 0.97 },
          { label: 2017, index: 1.01 },
          { label: 2018, index: 1.03 },
          { label: 2019, index: 1.08 },
          { label: 2020, index: 1.05 },
          { label: 2021, index: 1.0 },
        ],
        color: '#435EF2',
      },
      uncertainties: {
        data: [
          { label: 2006, min: 0.9, max: 1.1 },
          { label: 2007, min: 0.92, max: 1.21 },
          { label: 2008, min: 0.99, max: 1.29 },
          { label: 2009, min: 0.95, max: 1.25 },
          { label: 2010, min: 0.85, max: 1.15 },
          { label: 2011, min: 0.8, max: 1.02 },
          { label: 2012, min: 0.77, max: 0.99 },
          { label: 2013, min: 0.72, max: 0.95 },
          { label: 2014, min: 0.75, max: 1.0 },
          { label: 2015, min: 0.76, max: 1.06 },
          { label: 2016, min: 0.8, max: 1.1 },
          { label: 2017, min: 0.86, max: 1.15 },
          { label: 2018, min: 0.88, max: 1.18 },
          { label: 2019, min: 0.91, max: 1.21 },
          { label: 2020, min: 0.89, max: 1.18 },
          { label: 2021, min: 0.85, max: 1.15 },
        ],
        color: 'rgba(67, 94, 242, 0.1)',
      },
    }
```
**Je n'ai pas d'exigence particulière pour l'acquisition des données ponctuelles des encadrés de droite.**

**Comment by lpojgc** [comment]
données importées en BDD 

reste à faire les VM (cdnom + valeurs par an) et produire les API

**Comment by afourneyron** [comment]
VM pour les données issues d'enquêtes : src_survey.vm_carto_reg_information
information dispo :
- id
- nom_jdd
- cd_nom
- unite_graph (Nombre de dortoirs, nombre d'individus…,)
- type_graph (breed_count, breed_min_max, ...)
- id_area
- area_name (uniquement à l'échelle départementale) - /!\ les données des fichiers d'enquêtes ayant une entrée spatiale plus grande que les départements (PNR ou région) sont exclus de la synthèse) 
- geom
- last_date (pour la date la plus récente)
- value
- value_min
- value_max

**Comment by lpofredc** [comment]
Il manque les valeurs de tendances (blocs descriptifs) long terme et court terme.

![image](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/3d15082d-6a2d-407d-b8b9-a238798a1ed6)

**Comment by afourneyron** [comment]
Les valeurs de tendances (blocs descriptifs) ont été ajoutés uniquement pour les données Wetlands directement dans le format JSON dans la table t_representation sur le champ : champ_additionnel.

En ce qui concerne les données STOC qui sont dans le même cas, le problème est plus complexe.
Ce ne sont pas exactement les mêmes données, il nous manque quelques informations pour pouvoir mettre en place ses descriptions. @lpojgc un point avec Jérémie sera surement nécessaire.

**Comment by lpofredc** [comment]
Valeurs de tendances intégrées
