### ISSUE TITLE
Graphique tailles de populations (boxplot)

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#226]
### Boxplot avec médiane et indice de confiance
![populations_median](https://user-images.githubusercontent.com/57666163/152336465-8ce0b05b-d422-4777-a473-d640724dfdc5.png)

@lpofredc voilà comment j'ai construit les données pour d3.js : 
```
dataPopulations: {
  label: "Nombre d'individus",
  keys: ['Intervalle de confiance (90%)', 'Effectif médian'],
  data: [
    { label: '2001 - 2005', min: 95, median: 205, max: 315 },
    { label: '2005 - 2007', min: 210, median: 320, max: 430 },
    { label: '2007 - 2011', min: 300, median: 410, max: 520 },
    { label: '2011 - 2015', min: 280, median: 390, max: 500 },
    { label: '2015 - 2019', min: 170, median: 280, max: 390 },
    { label: '2019 - 2023', min: 230, median: 340, max: 450 },
  ],
  colors: ['rgba(67, 94, 242, 0.1)', '#435EF2'],
}
```

**Comment by lpojgc** [comment]
reste à faire :

- actualiser les VM et ajouter code territoire 
- produire les API

`SELECT
id_area
  , area_code
  , area_name
    FROM
ref_geo.l_areas
WHERE
id_type = ref_geo.get_id_area_type('ATLAS_TERRITORY')
;
`

**Comment by afourneyron** [comment]
VM pour les données issues d'enquêtes : src_survey.vm_graph_information 
information dispo : 
- nom_jdd
- cd_nom
- unite_graph (nombre de nids, nombre de couples, estimation individue…,) à voir pour la suite pour créer une variable qui contient l'ensemble des valeurs possibles des unités. 
- id_area (uniquement de ATLAS_TERRITORY) /!\ attention parfois vide si des données sont en-dehors des zones de l'ATLAS, on pense à certaines îles spécifiques qui ne sont pas encore de le ref_geo.l_areas de type ATLAS.
-  atlas_territory (nom du territoire) 
- date de début
- date de fin
- value
- value min
- value max

**Comment by lpofredc** [comment]
@afourneyron , il faudrait vérifier les données de suivi pour les cd_nom suivants (2844, 2856, 3089, 2852), le nombre de ligne pour ces espèces me parait suprenant. cf. requête suivante:

```sql
SELECT cd_nom,
       phenologie,
       COUNT(*) FILTER (WHERE phenologie LIKE 'wintering') AS nb_data_wintering,
       COUNT(*) FILTER (WHERE phenologie LIKE 'breeding')  AS nb_data_breeding
FROM src_survey.vm_graph_information
WHERE cd_nom IN (2844, 2856, 3089, 2852)
GROUP BY cd_nom, phenologie;
```

**Comment by lpojgc** [comment]
@lpofredc c'est OK, non ?

**Comment by lpofredc** [comment]
Echelle des ordonnée, plutôt restreindre à la zone de données:
- min - 10%
- max + 10%
