### ISSUE TITLE
Espèce nicheuse sur ODF sans donnée avec code atlas dans FF

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#244]
Bonjour,
Je n'ai pas trouvé dans [faune-france](https://www.faune-france.org/index.php?m_id=8&p_c=1&p_cc=-1&sp_tg=1&sp_DateSynth=04.04.2022&sp_DChoice=range&sp_DFrom=01.04.2019&sp_DTo=04.04.2022&sp_DCa=0&sp_SChoice=species&sp_S=33&sp_PChoice=grid&sp_Grid=450&sp_Grid_Info=E035N681&sp_AtlasCode=1&sp_Ats=-e_VS0&sp_project=0&sp_FChoice=list&sp_FGraphFormat=auto&sp_FMapFormat=none&sp_FDisplay=DATE_PLACE_SPECIES&sp_FOrder=ALPHA&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_DFormat=DESC&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FExportFormat=XLS) et faune-bretagne de donnée avec code atlas pour la Grande Aigrette sur la maille [E035N681](https://www.oiseauxdefrance.org/prospecting/?area=10kmL93E035N681&type=ATLAS_GRID)

Marc

**Comment by lpofredc** [comment]
C'est cette donnée qui a été modifiée durant la période de resynchronisation des bases de novembre 2021 (donnée initiale avec un code atlas 6) https://www.faune-france.org/index.php?m_id=54&id=79388086.

La donnée a jour bien intégré la base de donnée mais les données "GeoNature" n'ont pas été mis à jour en cascade.
Plus d'investigations sont en cours voir si d'autres données sont concernées.

**Comment by mgageo** [comment]
Une nouvelle donnée dans ce cas pour du Torcol fourmilier, [faune-france](https://www.faune-france.org/index.php?m_id=94&p_c=1&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.04.2019&sp_DTo=20.06.2022&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=333&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=0&sp_CommuneCounty=13&sp_Commune=4408&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E012N684&sp_Grid=11&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e_VS0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=04.04.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) et [odf maille n° E012N684](https://www.oiseauxdefrance.org/prospecting/?area=10kmL93E012N684&type=ATLAS_GRID)

**Comment by lpofredc** [comment]
@mgageo, pourriez-vous préciser?

Il n'existe en effet pas de donnée de nidif pour le Torcol sur cette maille. 

Mais la fiche maille ODF (espèces nicheuses) n'y fait pas non plus mention.

**Comment by mgageo** [comment]
Je ne vois effectivement plus le Torcol en espèce nicheuse.

**Comment by mgageo** [comment]
Mais sur E024N676 le Tadorne de Belon
![image](https://user-images.githubusercontent.com/2681495/177474191-92c631ec-8bc6-4e0d-8d05-a9f81005a970.png)

![image](https://user-images.githubusercontent.com/2681495/177474282-23022eaa-4d74-4d19-8c5d-368162945482.png)

**Comment by lpofredc** [comment]
Il s'agit de cette donnée, sur le lieu dit "Kerzard Ihuel". Ce lieu dit est à cheval sur deux mailles. De mémoire, visionature rattache les données aux mailles des lieu-dit tandis que le rattachement est recalculé pour chaque observation pour ODF.

[https://www.faune-france.org/index.php?m_id=54&id=77587442](https://www.faune-france.org/index.php?m_id=54&id=77587442)

![image](https://user-images.githubusercontent.com/22891423/177546868-7fb90b59-e402-48fe-b979-a8b484096f0a.png)

![image](https://user-images.githubusercontent.com/22891423/177547008-6d1892c3-0366-4f69-82a2-ae08a038687f.png)

**Comment by mgageo** [comment]
Ce n'est pas une observation précise, donc la localisation est celle du lieudit.
Et sur visionature les coordonnées lambert93 sont 243256.24999443267 6759999.253066209 soit E024N675.
Il doit y avoir une différence de conversion à partir des coordonnées wgs84 et je trouve les mêmes valeurs que visionature.

**Comment by mgageo** [comment]
Sur la maille E034N675, la Macreuse noire est nicheuse
![image](https://user-images.githubusercontent.com/2681495/177989651-58718589-3b62-48da-8493-f7d9c599b25c.png)

Je ne trouve pas de donnée sur [faune-bretagne](https://www.faune-bretagne.org/index.php?m_id=94&p_c=4&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.01.2019&sp_DTo=08.07.2022&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=133&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=0010&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E034N675&sp_Grid=393&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-5&sp_AltitudeTo=387&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e__S0&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_I=0&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=1&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=08.07.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) ni sur [faune-france](https://www.faune-france.org/index.php?m_id=94&p_c=1&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.04.2019&sp_DTo=08.07.2022&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=133&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=0&sp_CommuneCounty=13&sp_Commune=4408&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E034N675&sp_Grid=393&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e_VS0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=04.04.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher)

**Comment by mgageo** [comment]
Bonsoir,
J'ai encore des données présentes dans ODF et absentes de FF, par exemple [ff](https://www.faune-france.org/index.php?m_id=94&p_c=1&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.04.2019&sp_DTo=15.10.2023&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=531&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=0&sp_CommuneCounty=13&sp_Commune=4408&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E020N686&sp_Grid=99&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e_VS0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=04.04.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) [ODF](https://www.oiseauxdefrance.org/prospecting?area=10kmL93E020N686&type=ATLAS_GRID) pour E020N686 	Bruant des roseaux 

Marc

**Comment by lpofredc** [comment]
Bonsoir @mgageo,

La donnée "nicheur" en question est celle-ci: https://www.faune-france.org/index.php?m_id=54&id=87213919

Elle avait un code atlas 3, a priori modifié depuis, elle est marquée comme modifiée le 12 octobre 2023 et a bien été mise à jour côté bdd ODF. 

je vais voir pourquoi cette modification n'est pas répercutée dans ODF. 

Merci.

**Comment by lpofredc** [comment]
Pb identifié, une vue matérialisée a été modifiée la semaine dernière, son index unique était manquant faisant échouer le rafraichissement concurrentiel des données. C'est corrigé.
