### ISSUE TITLE
Espèce nicheuse sur ODF avec code atlas 1 dans faune-france

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#245]
Sur la maille E020N680 le faucon hobereau est noté nicheur possible alors que la seule donnée sur [faune-france](https://www.faune-france.org/index.php?m_id=94&p_c=1&p_cc=-1&sp_tg=1&sp_DChoice=range&sp_DFrom=01.04.2019&sp_DTo=04.04.2022&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=1&sp_DSeasonToDay=31&sp_DSeasonToMonth=12&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=174&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=0&sp_CommuneCounty=13&sp_Commune=4408&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E020N680&sp_Grid=93&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-e_VS0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=04.04.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) a un code atlas 1

**Comment by lpofredc** [comment]
C'est une question de référentiel. l'observation a un code atlas Biolovision de 2 (celui renvoyé par l'API). cf. [https://wiki.biolovision.net/index.php/Correspondance_codes_atlas](https://wiki.biolovision.net/index.php/Correspondance_codes_atlas).

Elle est donc considérée comme nicheuse possible et prise en compte pour l'atlas:

https://github.com/lpoaura/BirdAtlasOfFrance/blob/c720570cd7162df78317f80ae7b8d93e622e60c8/data/sql_scripts/001_data_for_atlas.sql#L45-L48

**Comment by mgageo** [comment]
En Bretagne on a tendance à ignorer les codes 2 qui sont mis un peu trop rapidement.
C'est donc une erreur de ma part, l'odf a raison, mes excuses pour le dérangement.
