### ISSUE TITLE
odf : certificat https expiré

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#247]
date de fin : Tue, 10 May 2022 10:43:10 GMT

**Comment by lpofredc** [comment]
Merci, c'est corrigé.

**Comment by A-d-r-i** [comment]
@lpofredc de nouveau expiré ce jour !

**Comment by lpofredc** [comment]
Pb de nouveau répété cette semaine, définitivement corrigé. 
Cause, la variable `-it` du cron sur le conteneur docker nginx permettant le renouvellement du certificat faisait planter la commande avec ce message d'erreur `the input device is not a TTY`...

requête en erreur
```crontab
5 3 * * * /usr/bin/docker exec -it nginx certbot renew > /home/geonature/log/renew.log
```

Bonne requête
```crontab
5 3 * * * /usr/bin/docker exec nginx certbot renew > /home/geonature/log/renew.log
```

**Comment by lpofredc** [comment]
Problème définitement résolu, le commentaire précédent était la solution. Renouvellement auto bien effectué.
