### ISSUE TITLE
ODF nicheurs : Effraie des clochers absente E019N680 	 

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#248]
La donnée https://www.faune-france.org/index.php?m_id=54&uid=46_4475838 ne semble pas prise en compte (code atlas 12)

**Comment by lpofredc** [comment]
Merci, lié à #170. 

C'est corrigé pour Tyto alba alba. Il va falloir mettre à jour les correspondances pour les autres taxons.

La donnée sera prise en compte à la prochaine MaJ.
