### ISSUE TITLE
Indisponibilité du site

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#265]
Bonjour à tous,
J'ai eu de nombreux échecs lors de la collecte sur la Bretagne un peu avant 14 heures.
Une maintenance en cours ?
Marc

**Comment by lpofredc** [comment]
Pas de maintenance du côté de l'application. Mais nous avons en effet eu des alertes de pertes d'accès aux serveurs (gérés par la LPO France) sur nos outils de monitoring peu avant 14h.

Merci pour ce retour.

**Comment by lpofredc** [comment]
Probablement lié à ce pb de réseau chez OVH (l'appli est sur un serveur OVH)

https://network.status-ovhcloud.com/incidents/5mldyhd6v99c
