### ISSUE TITLE
[monographie] restitution espèces sensibles

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#268]
prévoir la possibilité de restituer les données des espèces sensibles à une échelle à définir (département à confirmer)

**Comment by lpofredc** [comment]
@OiseauxdeFrance, préciser la demande.

**Comment by lpojgc** [comment]
@JeremyDupuy comment souhaites-tu que l'on fasse sur ces espèces (Bonelli, gypaete, grue, balbuzard, pygargue, percnoptère, PGPR, pomarin) ? On propose un dégradation au département, est-ce que c'est OK pour toi ? Il n'y a pas d'autre solution avec les zonages que l'on a...

**Comment by JeremyDupuy** [comment]
Ok pour les départements.

Exception pour le pomarin: à la maille

Exception pour la grue hors repro, où il faudrait avoir la carte à la maille (toute saison et hiver)

**Comment by lpofredc** [comment]
> Exception pour la grue hors repro, où il faudrait avoir la carte à la maille (toute saison et hiver)

Cas de figure "exceptionnel" difficile à gérer de manière générique, pourquoi ne pas élargir cette règle aux autres taxons "sensibles" ?

**Comment by lpofredc** [comment]
> Exception pour le pomarin: à la maille

Du coup c'est plus une espèce cachée? Il n'y a aucune restitution plus fine.

**Comment by JeremyDupuy** [comment]
Pour l'Aigle pomarin, on le sort des espèces cachées. On le traite comme une espèce normale.

Pour les autres, c'est difficile d'avoir une règle unique. Pour le Gypa, l'Aigle de Bonelli, ce sont des espèces sédentaires donc donner une carte à la maille hors repro revient à la même chose et je risque de recevoir des roquettes.

Pour les autres espèces sensibles, on pourrait faire le distingo entre la repro et le reste.

Voilà ça va être difficile de ne pas faire de cas particulier sur ce coup.


Jérémy Dupuy
Responsable de projet « Oiseaux de France »

Service Connaissance

Pôle Protection de la Nature

05.46.82.17.92
Fonderies Royales – CS 90263
17300 ROCHEFORT Cedex



[cid:788a8cad-cb0f-4e9c-9b6d-097b2257d4bc]
________________________________
De : Fred C ***@***.***>
Envoyé : lundi 6 novembre 2023 15:10
À : lpoaura/BirdAtlasOfFrance ***@***.***>
Cc : Jeremy Dupuy ***@***.***>; Mention ***@***.***>
Objet : Re: [lpoaura/BirdAtlasOfFrance] [monographie] restitution espèces sensibles (Issue #268)


Exception pour le pomarin: à la maille

Du coup c'est plus une espèce cachée? Il n'y a aucune restitution plus fine.

**Comment by lpojgc** [comment]
du coup si on en revient à notre proposition de restituer au département les sp sensibles, est-ce que ça pose un problème ?

**Comment by JeremyDupuy** [comment]
Ben ça me pose problème de restituer la carte hiver de la Grue cendrée au département. Idem pour d'autres espèces comme le Balbu ou le Pygargue.


Jérémy Dupuy
Responsable de projet « Oiseaux de France »

Service Connaissance

Pôle Protection de la Nature

05.46.82.17.92
Fonderies Royales – CS 90263
17300 ROCHEFORT Cedex



[cid:65a47208-d8e1-47c4-a92e-9318ab10a6df]
________________________________
De : Julien GC ***@***.***>
Envoyé : mardi 7 novembre 2023 11:50
À : lpoaura/BirdAtlasOfFrance ***@***.***>
Cc : Jeremy Dupuy ***@***.***>; Mention ***@***.***>
Objet : Re: [lpoaura/BirdAtlasOfFrance] [monographie] restitution espèces sensibles (Issue #268)


du coup si on en revient à notre proposition de restituer au département les sp sensibles, est-ce que ça pose un problème ?

**Comment by lpofredc** [comment]
C'est noté, demande un important travail de fond sur la structuration et la génération des données de l'appli. Il complexifie significativement la génération des données et sera possiblement impactante à l'avenir sur les performances du rafraichissement des données d'ODF.

**Comment by lpofredc** [comment]
Quel traitement pour les espèces à large répartition. Le Balbuzard étant aussi présent en Guyane et aux Antilles.

| area\_code | area\_name | lb\_nom | cd\_nom | nb données |
| :--- | :--- | :--- | :--- | :--- |
| 01 | Guadeloupe | Pandion haliaetus | 2660 | 948 |
| 02 | Martinique | Pandion haliaetus | 2660 | 137 |
| 03 | Guyane | Pandion haliaetus | 2660 | 5310 |
| 977 | Saint-Barthélemy | Pandion haliaetus | 2660 | 12 |
| 978 | Saint-Martin | Pandion haliaetus | 2660 | 21 |
| FRMET | France métropolitaine | Aquila fasciata | 2657 | 13918 |
| FRMET | France métropolitaine | Clanga pomarina | 836345 | 2107 |
| FRMET | France métropolitaine | Grus grus | 3076 | 312788 |
| FRMET | France métropolitaine | Gypaetus barbatus | 2852 | 35417 |
| FRMET | France métropolitaine | Haliaeetus albicilla | 2848 | 11640 |
| FRMET | France métropolitaine | Lanius minor | 3811 | 1629 |
| FRMET | France métropolitaine | Neophron percnopterus | 2856 | 20629 |
| FRMET | France métropolitaine | Pandion haliaetus | 2660 | 110386 |

**Comment by lpofredc** [comment]
On ajoute à la table des taxons 3 champs pour le zonage de restitution selon les périodes avec l'id type du zonage pour une restitution à la carte.

**Comment by lpofredc** [comment]
Modification faite en bdd:
Pour chaque taxon, un type de zonage est défini pour chaque période phénologique (par défaut, maille prédéfinie pour l'atlas, cf. #291 ). En l'état, les espèces sensibles sont représentées à la maille pour les périodes hiver et toute période, au département pour la période de reproduction.

Lors de la restition cartographique, les zonages affichés (mailles ou départements) sont filtrés par le type de zonage choisi pour l'espèce et la période. 

En conséquence, pour les espèces sensibles, lors des restitution hivernage et toute période, les données de reproduction sont exclues de la carte de distribution.

**Comment by lpofredc** [comment]
Le type de zonage des restitutions pour les espèces sensibles est maintenant personnalisable pour chaque taxon et chaque période phanologique. Le choix pris à ce jour pour les espèces sensibles est une dégradation au département pour les données de nidification.


![Capture d’écran 2023-11-16 à 14 58 54](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/0ada4508-4228-48f5-a7c3-ead6e7429418)


![Capture d’écran 2023-11-16 à 14 59 07](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/34dca949-a48b-4bef-a5b7-47670802d800)

![Capture d’écran 2023-11-16 à 14 59 23](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/28bdf45f-9114-479c-bca7-7f23e9d2fc94)
