### ISSUE TITLE
Données de début décembre 2022 non prises en compte 

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#275]
Bonjour,
On me signale (Jacques Maout) que malgré une "Dernière actualisation le 8 décembre 2022", des données ne sont pas prises en compte sur la maille E023N684 : Faucon pélerin, Héron cendré et Pic mar.
Il y a d'autres exemples.
Marc

**Comment by lpofredc** [comment]
Un travail de reprise des synchro depuis début décembre est en cours.

**Comment by mgageo** [comment]
Je viens d'avoir un retour de deux des trois observateurs qui m'avaient signalé des données non prises en compte.
La situation s'est rétablie en fin de semaine dernière.

**Comment by lpofredc** [comment]
Je ferme cette ancienne issue.
