### ISSUE TITLE
[monographie] txt de présentation

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#276]
Textes en cours de rédaction, 1er lot envoyé par JD fin janv deb février, import à prévoir dans la foulée

**Comment by lpojgc** [comment]
import en BDD les fichiers .docx
Attention à bien importer le nom du fichier dans une colonne pour la future correspondance taxref

**Comment by afourneyron** [comment]
Lecture des fichiers .docx fait
Correspodances taxref avec le nom du fichier fait
Import dans taxonomie.cor_taxon_attribut avec id_attribut 204 (description) fait

**Comment by lpofredc** [comment]
Sera cloturé une fois tous les textes à venir importés.

Le rendu du texte actuellement importé.

![Capture d’écran 2023-02-21 à 11 58 03](https://user-images.githubusercontent.com/22891423/220326550-a8b868b4-d862-41fc-a087-99ce9944e829.png)

**Comment by lpojgc** [comment]
je propose de cloturer et en faire un autre avec les futurs fichiers, pour des questions de lisibilité

**Comment by lpojgc** [comment]
modifications à mettre sur la bd prod

**Comment by lpojgc** [comment]
fait
