### ISSUE TITLE
[monographie] bdd traits de vie

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#277]
JD envoie fin janvier la BDD traits de vie avec les correspondances taxref.

Ne traiter que les sp avec correspondances.

Peut être nouvelle version + tard avec plus d'espèces et d'autres infos.

**Comment by lpojgc** [comment]
20/02 : BDD plus dispo

**Comment by lpofredc** [comment]
Les données peuplées sont:

- Répartition et déplacements
- Alimentation
- Habitat
- Reproduction
- Taille de population
