### ISSUE TITLE
[données] intégration données opportunistes Normandie

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#278]
Fichier va être transmis contenant : 
- maille
- commune
- sp
- année
- code atlas (30-40-50)

Pour les données hivernant et nicheurs

**Comment by lpojgc** [comment]
données reçues, à intégrer

**Comment by lpojgc** [comment]
Pour l'import :
-    importer en synthèse et peupler la synthèse étendue
-    pensez à JDD, CA et sources
-    désactiver trigger
-    peupler update/create date
-    peupler la géométrie avec le polygone de la maille

**Comment by afourneyron** [comment]
Données intégrées (39 409) dans le JDD 1239
