### ISSUE TITLE
[données] intégration données atlas Normandie 

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#279]
Fichier va être envoyé avec :
- maille
- sp
- année
- statut max repo
Concerne la période 2016-2019

**Comment by lpojgc** [comment]
données reçues, à intégrer

**Comment by lpojgc** [comment]
2 mentions dnas le fichier nidification et hivernage.
Pour l'import :
- importer en synthèse et peupler la synthèse étendue
- pensez à JDD, CA et  sources
- désactiver trigger
- peupler update/cretae date
- pour les données hivernants : date_min = 01/01 de l'année et date_max = 31/01 de l'année
- pour les données de reprod : date_min = 15/05 de l'année et date_max = 15/05

**Comment by afourneyron** [comment]
Ensembles des données intégrées dans 2 jeux de données pour les périodes hivernants et reproduction : 
Hivernant 41303 données sur le JDD 1241
Reproduction 46 945 données sur le JDD 1240
