### ISSUE TITLE
[données] intégration données eBird

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#280]
JD va envoyer les données à intégrer avec les codes atlas (30/40/50).

Garder en tête la possibilité d'exclure des données invalidées ultérieurement.

**Comment by lpojgc** [comment]
données reçues, à intégrer

**Comment by lpojgc** [comment]
Données à inétgrer en synthèse et synthèse étendue.
Traduction des codes atlas : 
- 30 possible
- 40 probable
- 50 certain
Penser à faire une source dédiée dans t_sources

**Comment by lpojgc** [comment]
apparemment des cd_nom inexistants dans le fichier, à voir comment les gérer (crétaion de cd_nom négatifs ou écartement des données)

**Comment by afourneyron** [comment]
On a écarté les données ayant un cd_nom inexistants ou sans correspondances 
Le reste des données est sur le JDD id = 1238 (ebird_data_2023) et la source = 26 (Import eBird)

Pour les espèces sans correspondances, on retrouve  : 

- "Salangane des Nouvelles-Hébrides"
- "Amazone d'Hispaniola"
- "Souimanga angaladian"
- "Méliphage foulehaio"
- "Grive à collier" 
- "Pie-grièche boréale"             
- "Siffleur mélanésien"
- "Bécarde verte"
- "Pic à dos rayé"                  
- "Piranga à tête rouge"
- "Puffin de Parkinson"
- "Pétrel de Henderson"             
- "Pétrel de Stejneger"
- "Puffin de Newell"
- "Paruline de Townsend"            
- "Bruant des plaines"
- "Martin-chasseur du Pacifique"
- "Viréo jaune-verdâtre"            
- "Viréo mélodieux"

**Comment by lpojgc** [comment]
@afourneyron , pourras-tu vérifier les correspondances existent maintenant ? plusieurs ont été intégrées.
si les correspondances existent bien, il faudrait importer ces données.
merci

**Comment by lpojgc** [comment]
voir https://github.com/lpoaura/BirdAtlasOfFrance/issues/324

**Comment by afourneyron** [comment]
Il reste encore 3 espèces sans correspondances : 
Collocalia uropygialis   | Salangane des Nouvelles-Hébrides (863 données)
Pachycephala chlorura | Siffleur mélanésien (27 données)
Vireo flavoviridis          | Viréo jaune-verdâtre (2 données)

**Comment by afourneyron** [comment]
Intégration de 180  données avec les 16 nouvelles espèces avec correspondances (Picoides dorsalis, Pterodroma longirostris, anius borealis, Foulehaio carunculatus, Procellaria parkinsoni, Pterodroma atrata, Vireo gilvus, Todiramphus sacer, Spizella pallida, Piranga ludoviciana, Pachyramphus viridis, Cinnyris notatus, Puffinus newelli, Setophaga townsendi, Ixoreus naevius, Amazona ventralis)
Fait

**Comment by lpojgc** [comment]
> Il reste encore 3 espèces sans correspondances : Collocalia uropygialis | Salangane des Nouvelles-Hébrides (863 données) Pachycephala chlorura | Siffleur mélanésien (27 données) Vireo flavoviridis | Viréo jaune-verdâtre (2 données)

@afourneyron , as-tu regardé dans le fichier de JD si ces taxons avaient un cd_nom ? il est possible qu'il y a des synonymes avec des espèces que l'on a déjà traitées

**Comment by afourneyron** [comment]
Oui pour ses espèces il y a des cd_nom d'indiquer mais aucun de ses cd_nom n'est présent dans taxref.
(962459, 962462, 977555)
 
962459 | Collocalia uropygialis 
962462 | Pachycephala chlorura
977555 | Vireo flavoviridis

**Comment by lpojgc** [comment]
ok, c'est donc lié à la version de taxref qui n'est pas la plus récente sur cette bdd.
@lpofredc je pense qu'on pourrait insérer les cd_nom en question dans taxref pour pouvoir traiter ces espèces, qu'en pesnes-tu ?

**Comment by afourneyron** [comment]
Dernières données sont intégrées

au total sur la base de donnée on a : 530 501 données de ebird
Le fichier excel contient 530 503 mais il y a 2 données sans dates qui ont été mis de côté.

**Comment by lpojgc** [comment]
parfait, merci !
