### ISSUE TITLE
Différence entre l'api "area/knowledge_level" et l'affichage sur le site web

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#284]
On vient de me remonter une différence pour la maille E020N686 pour les espèces en hiver après 2019.

Sur le site web, le nombre indiqué est de 100 alors que la requête https://www.oiseauxdefrance.org/api/v1/area/knowledge_level/ATLAS_GRID?envelope=-3.81,48.6,-3.66,48.8 indique 99
Je n'ai pas testé sur d'autres mailles.

Site internet
![image](https://user-images.githubusercontent.com/2681495/212535196-60c7b70d-6589-46be-8c73-70c4061c1bbf.png)

api
![image](https://user-images.githubusercontent.com/2681495/212535159-5ef01a7b-c115-44dd-b989-eb76a126e5b6.png)

**Comment by lpofredc** [comment]
Origine de la différence trouvée, dans la synthèse par maille, les données hivernales avec code atlas nicheur étaient exclues. Sont considérées comme données hivernales TOUTES les données de la période hivernale, même les données avec code nidif.

**Comment by mgageo** [comment]
Il ne faut pas prendre toutes les données hivernales : par exemple celles avec code atlas 99 Espèce absente malgré des recherches

**Comment by lpofredc** [comment]
Oui, elles sont exclues en amont. cf. https://github.com/lpoaura/BirdAtlasOfFrance/blob/main/docs/docs/data.md#observation-status
