### ISSUE TITLE
Donnée en cours de vérification prise en compte 

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#287]
Bonjour,
La Sterne pierregarin est indiquée comme présente en hiver sur la maille E018N677 alors que la seule donnée présente dans [faune-france](https://www.faune-france.org/index.php?m_id=94&p_c=3&p_cc=-1&sp_tg=1&sp_DFrom=17.11.2021&sp_DTo=16.01.2023&sp_DChoice=season&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=12&sp_DSeasonToDay=31&sp_DSeasonToMonth=1&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=293&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E018N677&sp_Grid=67&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_OnlyAH=0&sp_Ats=-00000&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=16.01.2023&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) est en cours de validation :

**Comment by lpofredc** [comment]
Ok, merci pour ce retour. 

Nous avons eu un pb de synchro durant les fêtes de noel et constaté des plusieurs jours avec des données manquantes cet automne, nous avons relancé une synchro des données depuis septembre dernier mais avec une entrée date d'obs, cette donnée (de l'hiver dernier et modifier le 23/12 dernier n'a donc pas été mise à jour). Je viens de relancer une correction des données avec un filtrage sur la date de saisie/mise à jour. 

cela devrait fixer ce pb dans la semaine.

**Comment by lpofredc** [comment]
Pb corrigé, la donnée n'est plus prise en compte. Merci
