### ISSUE TITLE
[carte additionelles] choix de légende

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#290]
déifnir la légende pour les départements sans données

**Comment by lpojgc** [comment]
@JeremyDupuy , OK pour toi ?

**Comment by JeremyDupuy** [comment]
Je mettrai:

- pour le bleu: Présence de l'espèce
- pour le gris: Absence de l'espèce 

Et on précise en haut de la légende: Carte de présence du Milan royal lors du comptage national des dortoirs (2022)..

**Comment by lpofredc** [comment]
Libellés choisis:

Existence de données de suivis
Absence de données de suivis.

![Capture d’écran 2023-11-16 à 14 49 54](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/f94e064b-5baa-4098-aafa-acdaf8e394d0)
