### ISSUE TITLE
affichage maillage

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#293]
JD : Lorsqu'on dézoome, les pastilles rondes sont encore sur le format mailles de 10km pour des territoires comme la Martinique ou la Guadeloupe, ce qui fait que les pastilles se superposent.

**Comment by lpofredc** [comment]
Corrigé ici: https://github.com/lpoaura/BirdAtlasOfFrance/commit/69a2e6df5371c453c95cdd7f1bc7bd70309c8922


![Screenshot 2023-03-30 at 09-59-00 Atlas des Oiseaux de France](https://user-images.githubusercontent.com/22891423/228769789-ed2824c2-89a6-466a-9269-7da4b3b85852.png)
