### ISSUE TITLE
espèce absente ?

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#294]
JD : il y a des espèces qui ne s'affichent pas encore, par exemple le pic de Guadeloupe.
JGC : est-ce simplement une question de rafraichissement de vm ou réellement un pb ?

**Comment by lpojgc** [comment]
pn normalement réglé mais besoin de peupler les noms vernaculaires dans taxhub

**Comment by lpojgc** [comment]
pn normalement réglé mais besoin de peupler les noms vernaculaires dans taxhub

**Comment by lpofredc** [comment]
Fait
