### ISSUE TITLE
[communes] ajouter communes outre mer

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#296]
JD
Sur ce lien, tu trouveras les shapes des communes dans les dossiers suivants:
- [x] Global_sans PF_NC: tous les territoires excepté Polynésie et Nouvelle-Calédonie (contient donc SPM, SM, SB et les TAAF)
- [x] Polynésie-Française
- [x] Nouvelle-Calédonie

[Limite Commune](https://lpo061-my.sharepoint.com/:f:/g/personal/jeremy_dupuy_lpo_fr/EveQCcc7ccVFhhSYvvSe0JEBL9LrPmqDmfPpdoXQa4k0Tg?e=giNqbD)

**Comment by lpojgc** [comment]
JD
Sur ce lien, tu trouveras les shapes des communes dans les dossiers suivants:
- Global_sans PF_NC: tous les territoires excepté Polynésie et Nouvelle-Calédonie (contient donc SPM, SM, SB et les TAAF)
- Polynésie-Française
- Nouvelle-Calédonie

[Limite Commune](https://lpo061-my.sharepoint.com/:f:/g/personal/jeremy_dupuy_lpo_fr/EveQCcc7ccVFhhSYvvSe0JEBL9LrPmqDmfPpdoXQa4k0Tg?e=giNqbD)

**Comment by lpofredc** [comment]
Pour la polynésie française, il est nécessaire de revoir la couche:
* Fusionner les polygones par champs `nom` et `code_com_i`
* Simplifier les géométries. La couche, basée sur le cadastre est bien trop précise et lourde pour un usage dans ODF.

**Comment by lpofredc** [comment]
Polynésie française simplifiée (environ 100m entre chaque noeuds)
