### ISSUE TITLE
[monographie] bug affichage carte

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#297]
Quand on sélectionne le pic de guadeloupe depuis la page d'accueil :

- la carte se centre sur la métropole et dit pas de données (comportement normal)
- si on sélectionne la Guadeloupe, on a encore un emssage pas de données => bug
- si on sélectionne une période, les données apparaissent.

Sur mon premier essai, ça a fonctionné mais j'ai eu ce comportement en faisant Guyane puis Guadeloupe

**Comment by lpofredc** [comment]
Résolu dans la version future
