### ISSUE TITLE
[monographie] graphique phéno

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#305]
le diagramme phéno en période de repro pour le gardeboeuf plante quand on passe de la métropole à Guyane à Martinique par exemple

![image](https://user-images.githubusercontent.com/51160496/234542601-5e5d41f7-07d6-4271-be88-f5224de0a47f.png)

**Comment by lpofredc** [comment]
Corrigé, on affiche plus les séries sans données et l'affichage du graphique est maintenant conditionné l'existence de données positives.
