### ISSUE TITLE
[monographie] gestion des graphiques wetlands

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#310]
2 types d'espèces :

- sp pour lesquelles on n'a que des effectifs, pas de tendances (25 sp)
- sp pour lesquelles on a des tendances (66 sp).

**1. Espèces avec effectif seulement**
- restitution sous la forme d'histogramme seulement
- données dans onglet histo25sp, attention à bien intégrer les 0 et à ne pas en générer d'autres
@afourneyron il faudrait intégrer les données
@lpofredc il faudra faire les graphes apèrs intégration des données

**2. Espèces avec tendances**
- restitution selon ![odf_wi_sp_tendances](https://github.com/lpoaura/BirdAtlasOfFrance/assets/51160496/41a13881-f368-4bf1-8fec-9ad5d03b8ac9)
- données dans onglet indice66
- info :
       - courbe bleue : index_imputed
       - courbe grise : modl
       - + intervalle confiance sup et inf
       - info sur les tendances (texte à droite, dans onglet trend_66sp - long terme et court terme)
@afourneyron il faudrait intégrer les données
@lpofredc il faudra faire les graphes apèrs intégration des données

**3. informations complémentaires**
Pour toutes les sp (91), il faudrait faire figurer en complément :
- nb individus et sites : dernière année de max de totNat91sp
- dernière valeur de ENMC (onglet ENMC91sp)
@lpofredc => à discuter sur la manière de représenter les données

**Comment by lpojgc** [comment]
pb sur le graphique de tendances, possibilité de restituer 3 informations par année et pas 4, voir laquelle éliminer

**Comment by afourneyron** [comment]
Intégration de l'ensemble des données sur le schéma src_survey 
association d'un JDD par onglet : 
id_dataset = 1323 -> onglet Histo25sp
id_dataset = 1325 -> onglet Indices66sp
id_dataset = 1326 -> onglet TotNat91sp
id_dataset = 1327 -> onglet Trend66sp 

Pour le JDD 1327 (Trend66sp) : insertion des valeurs -99999 avec l'ensemble des informations en commentaire au format JSON pour retrouver facilement l'ensemble des paramètres textuel. 

Pour le JDD 1325  (Indices66sp) : insertion des valeurs : Index_imputed, Modl, CIinf95, CIsup95 a l'unité 'Tendance' sauf pour Modl à l'unité 'Tendance_moyenne' pour être exclu lors du graphique afin d'afficher uniquement Index_imputed, CIinf95, CIsup95 sur le graphique.


Création des graphiques associés aux JDD pour l'ensemble des espèces présentes : 
1323 -> onglet Histo25sp -> breed_count (Nombre d'individus)
1325 -> onglet Trend66sp -> breed_min_max (Tendance)
1326 -> onglet TotNat91sp -> breed_count (Effectif cumulé à l'année)

**Comment by lpojgc** [comment]
sur le graphique, on ne restitue pas la ligne sombre (vu avec JD)

**Comment by lpofredc** [comment]
Graphique de tendance intégré, se pose la question de la période restituée. En l'état, cela restitue les données de 1980 à 2022 avec un graphique à faire défiler pour tout visualiser.

![image](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/1acda97b-f282-4616-b9c2-fa6de3c9772c)

**Comment by lpofredc** [comment]
Graphiques intégrés:

![Capture d’écran 2023-10-25 à 22 16 42](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/e9a02d4a-b6c8-48e4-8862-95e76508b8a6)

**Comment by lpojgc** [comment]
on cloture ?

**Comment by lpofredc** [comment]
oui
