### ISSUE TITLE
[monographie] carte atlas historiques

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#312]
sur la version de dev, il y a différents pb d'affichage :
- affichage au département au lieu de la maille
- pb de titre (breedin / wintering)
- multiplication des entrées dnas le menu de gauche sans tenir compte du filtre de période à droite

![Capture d’écran du 2023-06-14 16-32-47](https://github.com/lpoaura/BirdAtlasOfFrance/assets/51160496/7fc91cdd-56c2-4b62-a1dd-2f2f3f896ad5)
![Capture d’écran du 2023-06-14 16-33-23](https://github.com/lpoaura/BirdAtlasOfFrance/assets/51160496/86678dab-0892-4129-907f-449eef90f833)

**Comment by lpofredc** [comment]
Pb résolu par un fix des données du référentiel geographique et des données historiques
