### ISSUE TITLE
[monographie] nom vernaculaire

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#316]
pour les monographies, faire apparaitre prioritairement le nom vernculaire ODF, à défaut nom vern taxref à défaut nom scientifique

**Comment by lpofredc** [comment]
Fait in https://github.com/lpoaura/BirdAtlasOfFrance/commit/6d9d9ab787c583d4ae3637de53b3587ccddddb1c
