### ISSUE TITLE
[import données] NatureOCentre

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/BirdAtlasOfFrance#317]
**Nature'O'Centre** mettra a disposition **deux** fichiers **tsv** (séparateur tabulation) à télécharger sur le serveur:

- Un fichier des données supprimées

nom du champ | type | detail
-- | -- | -- 
entity_source_pk_value | text | identifiant de la données dans la base de données d’origine
uuid | UUIDV4 | Identifiant unique universel
date_sup | timestamp | Date de suppression

- Un fichier des données à intégrer avec les champs suivants

nom du champ | type | détail
-- | -- | --
entity_source_pk_value | text | identifiant de la données dans la base de données d’origine
uuid | UUIDV4 | Identifiant unique universel
cd_nom | entier | cd_nom issu de taxref
altitude_min | reel | altitude de l’observation
date_min | date | date de l’observation, sur la base d’une date précise
bird_breed_code (code atlas) | entier | sur la base des « codes biolovision » https://wiki.biolovision.net/Correspondance_codes_atlas
'Migration active' | booleen | oui pour les données de migration, non pour les autres
cd_nomenclature_observation_status | text | No : non observé, Pr : présent
geom | text | au format texte généra avec la fonction postgis `st_astext(geom)`
cd_sig | text | Code de référence de la maille 10x10 sinp
commentaire | text | Commentaire de l'observation
date_maj | timestamp | Date de dernière action (INSER/UPDATE)

L'accès pourra être protégé par une authentification basique http (`htpasswd`) configuré sur le proxy du serveur de Nature'O'Centre.

La mise à jour d'ODF avec ces données sera hebdomadaire avec processus automatisé de téléchargement des données et un traitement des suppression, insertion et mises à jour à partir des dates (`date_maj` & `date_sup`) fournies dans les fichiers. 
Fournir les données à partir du 01/01/2007.

**Comment by lpofredc** [comment]
Premier lot de données intégrées

**Comment by marineteneur** [comment]
Script automatique de mise à jour mis en place
