### ISSUE TITLE
Trame fiche espèce

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#318]
Sans le tableau pour intégrer les textes des fiches espèces, Julien tu as crée un champ synonymes dans lequel tu as mis les taxons subspecifiques. Par synonymes, je voulais parler des noms vernaculaires synonymes (comme vu avec toi, ceux proposés dans TaxRef sont obsolètes).

Dois-je bien mettre le synonymes dans ce champs synonymes et laisser les informations des sous-espèces dans le champs "Description" avec un saut de ligne? 

Merci

**Comment by lpofredc** [comment]
En effet, ce champ sert aux sous-espèces, il a été renommé.
Concernant les noms principaux et synonymes, ils sont définis comme suit:
Nom français: Nom venant de Visionature sinon (c'est à dire si pas de valeur dans VisioNature) premier nom cité de TaxRef
Synonymes: noms suivants de TaxRef (sans le premier nom cité donc)

Toutes ces valeurs sont éditables dans le taxhub dédié:
![image](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/3ea2fdb7-72b3-4353-87e7-6a083508c708)

**Comment by JeremyDupuy** [comment]
Bonjour,

Dans le tableau partagé "trame fiche espèce" (https://lpo061-my.sharepoint.com/:x:/r/personal/julien_girard-claudon_lpo_fr/_layouts/15/Doc.aspx?sourcedoc=%7B550E7CED-4A96-4CD4-BECC-AE71D588C4C3%7D&file=trame_fiche_espece.xlsx&action=default&mobileredirect=true), vous trouvez près de 200 textes pour intégration dans les fiches-espèces ODF. J'ai essayé de respecter les codes pour l'écriture italique et le saut de ligne.

Bonne journée,
