### ISSUE TITLE
MAJ CD-NOM taxon manquant

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#319]
Bonjour,

Marine a créé les taxons qui manquaient dans le TaxREF. J'ai intégré les nouveaux CD-NOM dans les tables de listes d'espèces correspondant aux différents territoires OM (j'ai laissé une table par territoire car il y a les infos des winter_period).
Disponible ici: 
https://lpo061-my.sharepoint.com/:f:/g/personal/jeremy_dupuy_lpo_fr/EsN3FjQQZaRIqi1LZVYnh-oBWfDZKSnFqdwDNwQdntzU_w?e=dHJGVT

Merci

**Comment by lpojgc** [comment]
@lpofredc à cloturer ?
