### ISSUE TITLE
Nom vernaculaire faune-réunion

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#320]
Bonjour,

J'ai remarqué que le nom vernaculaire des espèces à la Réunion sont le nom donné dans TaxRef et non celui de Biolovision.

Par exemple, le Gobe-mouches de Paradis (CD_NOM=442419) dans TaxRef qui est en réalité le Terpsiphone de Bourbon (Tchitrec des Mascareignes) das Biolovision.

A vérifier aussi pour d'autres taxons dans faune-mayotte et faune- antilles.

Merci

**Comment by lpofredc** [comment]
Corrigé, merci.
