### ISSUE TITLE
Données Saint-Martin et saint-Barthélémy

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#321]
Re,

Malgré la connexion de faune-antilles, les données n'apparaissent toujours pas sur ODF à Saint-Martin et SAint-Bart.

Merci

**Comment by JeremyDupuy** [comment]
Merci Fred.

Concernant les indices de complétude par maille, lorsqu'il y a 0 sp sur la période avant 2019, mais des espèces après 2019, on se retrouve avec un indice de complétude de 0%. Faudrait que l'on donne une valeur par défaut à ces mailles pour éviter qu'elles n'apparaissent transparentes.

**Comment by lpofredc** [comment]
Données importées, Nouveau ticket pour le commentaire https://github.com/lpoaura/BirdAtlasOfFrance/issues/321#issuecomment-1663443913
