### ISSUE TITLE
Corneille noire/mantelée

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#322]
Je reviens sur les échanges que l'on avait eu fred par mail le 19/07 dernier, sur les taxons Corneille noire et Corneille mantelée. Il me semblait que le changement avait été fait mais sur les cartes ODF actuelles, on a toujours le taxon Corneille noire (CD Nom 4503) qui englobe la Corneille mantelée. Tu peux vérifier sp

**Comment by lpofredc** [comment]
Corrigé.

![Capture d’écran 2023-09-21 à 15 15 42](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/4b8b8543-f3ad-4394-9b3d-b595458cabd1)


![Capture d’écran 2023-09-21 à 15 15 32](https://github.com/lpoaura/BirdAtlasOfFrance/assets/22891423/4291d8cb-38c6-4401-9839-260ca795817e)
