### ISSUE TITLE
Faucon pèlerin (F.p.brookei) 

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#323]
Bonjour,
Cette espèce est apparue relativement récemment.
![image](https://github.com/lpoaura/BirdAtlasOfFrance/assets/2681495/6428967e-58ef-46c4-a8f2-e6594206bce5)

**Comment by mgageo** [comment]
Et cela doit être aussi le cas pour Cisticole des joncs (C.j.cisticola)

**Comment by lpofredc** [comment]
Merci, problème corrigé.
