### ISSUE TITLE
Import jeux de données GON et PN Pyrénées

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#325]
Bonjour,

Deux jeux de données à importer dans ODF:
- [x] GON (https://lpo061-my.sharepoint.com/:f:/g/personal/jeremy_dupuy_lpo_fr/EjYxuunSv95NjzlaB8eKCpwBLgKrgP0BmkJZlpfkvwQElg?e=dg7r3k)
- [x] Pn Pyrénées (https://lpo061-my.sharepoint.com/:f:/g/personal/jeremy_dupuy_lpo_fr/EupulE8pww1Hgk_0wsBIfxsBT5iVXTje2kS1vpBnFjDYkw?e=hAPb5j)

Merci,

**Comment by afourneyron** [comment]
Bonjour, 

je suis en train d'analyser les jeux de données avant l'import concernant le fichier GON, je voudrais m'assurer de la géométrie à intégrer. 
Il y a à la fois une référence de maille et les coordonnées X et Y.
Cependant, les coordonnées X et Y sont parfois non renseignées (presque 50% des données) 

Dois-je intégrer à la maille pour l'ensemble des données, ou intégrer aux coordonnées X et Y lorsque cela est possible ?

**Comment by lpojgc** [comment]
@JeremyDupuy , peux tu répondre à Axel stp ?
Je lui avais dit d'intégrer les données aux X/Y et que l'on ferait le rattachement ensuite mais il n'y a pas des coordonnées partout, que doit il faire ?

**Comment by JeremyDupuy** [comment]
Pour les données avec des X et Y, ce sont des données qui ont été collectées au point, comme sur VisioNature --> pour celles là pas de problème
Pour les données sans X et Y, il s’agit de données qui sont saisies au polygone ou au transect, certains pouvant être à cheval sur plusieurs mailles ou communes. Dans l'export que m'a transmis le GOn, je leur ai demandé d'ajouter l'information de la maille en se basant sur le centroïde de la géométrie de saisie. c'est l'information id_maille. Pour ces données, il faut donc utiliser l'id de la maille.
Donc s'il y a qu'une seule possibilité intégration (soit maille, soit x et y), alors on intègre à la maille.

**Comment by afourneyron** [comment]
Salut @JeremyDupuy et @lpojgc 
Nous avons lancé l'intégration des données du fichier GON (plus de 1 104 731) assez conséquentes et lourde pour le serveur. 
Mais nous avons arrêté l'import, car nous nous sommes aperçus qu'il y a des doublons parmi le fichier (39 275).

Ses doublons sont sur la base d'avoir la même valeur sur les champs : 
entity_source_pk_value, cd_nom, LB_NOM, geom,  date_min. 

Est-ce que nous mettons ses données de côté, ou est-que nous les intégrons mais seulement en 1 exemplaire ?

Bonne journée à vous.

**Comment by JeremyDupuy** [comment]
Bonjour,

Oui faisons comme ça.

Merci,



Jérémy Dupuy
Responsable de projet « Oiseaux de France »

Service Connaissance

Pôle Protection de la Nature

05.46.82.17.92
Fonderies Royales – CS 90263
17300 ROCHEFORT Cedex



[cid:48f9eb11-2a3b-46db-a012-779d21a1f053]
________________________________
De : Axel F ***@***.***>
Envoyé : jeudi 16 novembre 2023 11:06
À : lpoaura/BirdAtlasOfFrance ***@***.***>
Cc : Jeremy Dupuy ***@***.***>; Mention ***@***.***>
Objet : Re: [lpoaura/BirdAtlasOfFrance] Import jeux de données GON et PN Pyrénées (Issue #325)


Salut @JeremyDupuy<https://github.com/JeremyDupuy> et @lpojgc<https://github.com/lpojgc>
Nous avons lancé l'intégration des données du fichier GON (plus de 1 104 731) assez conséquentes et lourde pour le serveur.
Mais nous avons arrêté l'import, car nous nous sommes aperçus qu'il y a des doublons parmi le fichier (39 275).

Ses doublons sont sur la base d'avoir la même valeur sur les champs :
entity_source_pk_value, cd_nom, LB_NOM, geom, date_min.

Est-ce que nous mettons ses données de côté, ou est-que nous les intégrons mais seulement en 1 exemplaire ?

Bonne journée à vous.

**Comment by afourneyron** [comment]
Très bien je lance l'intégration des 1 057 598 données et je clos le ticket une fois intégré.

**Comment by lpofredc** [comment]
Données intégrées à ODF en décembre
