### ISSUE TITLE
zonages autres que départementaux pour les données de suivi

### ISSUE THREAD

**Issue by lpojgc** [lpoaura/BirdAtlasOfFrance#329]
@afourneyron peux-tu lister les espèces et les zonages concernées dans les données de suivi, qui ne sont pas des départements ?

**Comment by lpojgc** [comment]
pour compléter le ticket ici (en lien ave l'autre ticket), le but est de travailler sur la restitution de ces données sur les cartes

**Comment by lpojgc** [comment]
Choix fait de rester sur des restitutions aux départements pour les cartes (données à récupérer pour la dernière année seulement)
Pour les graphiques (et donc les données historiques), on peut rester sur les données à l'échelle des massifs

**Comment by lpofredc** [comment]
Ticket à clore donc
