### ISSUE TITLE
API unique de synthèse des espèces par zonage (maille)

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/BirdAtlasOfFrance#33]
Je propose de fusionner en une unique API les attentes des tickets #11, #10, #4, #5 listant pour une zone (maille) et pour chacune des espèces:
* Toute saison:
  * Présence durant la période de référence 
  * Présence durant la nouvelle période
* Hivernage:
  * Présence durant la période de référence 
  * Présence durant la nouvelle période
* Reproduction:
  * Présence durant la période de référence 
  * Présence durant la nouvelle période
  * Statut nicheur max durant la période de référence
  * Statut nicheur max durant la nouvelle période

Répondant ainsi aux attentes des tickets #11, #10, #4, #5

**Comment by lpofredc** [comment]
Concerne aussi #14

La structure des données de l'API serait la suivante:
* cd_nom taxref
* Nom scientifique taxref
* Nom vernaculaire taxref
* Toute saison:
  * Présence durant la période de référence
  * Présence durant la nouvelle période
  * Dernière année d'observation
* Hivernage:
  * Présence durant la période de référence
  * Présence durant la nouvelle période
  * Dernière année d'observation
* Reproduction:
  * Présence durant la période de référence
  * Présence durant la nouvelle période
  * Statut nicheur max durant la période de référence
  * Statut nicheur max durant la nouvelle période
  * Dernière année d'observation

**Comment by eguilley** [comment]
🔤 Si cela est faisable, il faudrait ranger les espèces par ordre alphabétique selon leur nom commun

**Comment by lpofredc** [comment]
Et privilégier les noms communs issus de VisioNature
