### ISSUE TITLE
Phénologie de migration pour fiche espèce

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#330]
Bonjour,

le phénologie de migration sont prêtes (enfin!).

Elles sont dispo dans les vues matérialisées : 
- lpofrance_mte.pheno_migration_etape7_quantiles_choix_traitement_esp_d (espèces à deux phénos de migration)
- lpofrance_mte.pheno_migration_etape6_4_quantiles_esp_spe_d (espèces à une seule phéno)

Merci,

**Comment by JeremyDupuy** [comment]
Bonjour Fred,

Les réponses :

Vue matérialisée pheno_migration_etape7_quantiles_choix_traitement_esp_d

  *   cd_nom
  *   traitement : traitement appliqué pour l'espèce déterminant les quantiles
  *   q2_5_printemps_d : quantile 2,5 en décade pour la période de printemps de l'espèce
  *   q5_printemps_d : quantile 5 en décade pour la période de printemps de l'espèce
  *   q25_printemps_d : quantile 25 en décade pour la période de printemps de l'espèce
  *   mediane_printemps_d : quantile 50 en décade pour la période de printemps de l'espèce
  *   q75_printemps_d  : quantile 75 en décade pour la période de printemps de l'espèce
  *   q95_printemps_d : quantile 95 en décade pour la période de printemps de l'espèce
  *   q97_5_printemps_d : quantile 97,5 en décade pour la période de printemps de l'espèce
  *   q2_5_automne_d : quantile 2,5 en décade pour la période d'automne de l'espèce
  *   q5_automne_d : quantile 5 en décade pour la période d'automne de l'espèce
  *   q25_automne_d : quantile 25 en décade pour la période d'automne de l'espèce
  *   mediane_automne_d  : quantile 50 en décade pour la période d'automne de l'espèce
  *   q75_automne_d : quantile 75 en décade pour la période d'automne de l'espèce
  *   q95_automne_d : quantile 95 en décade pour la période d'automne de l'espèce
  *   q97_5_automne_d : quantile 97,5 en décade pour la période d'automne de l'espèce
  *   decade_charniere : décade charnière entre le printemps et l'automne de l'espèce

Vue matérialisée pheno_migration_etape_6_4_quantiles_esp_spe_d

  *   cd_nom
  *   q2_5_d : quantile 2,5 de l'espèce
  *   q5_d : quantile 5 de l'espèce
  *   q25_d : quantile 25 de l'espèce
  *   mediane_d : quantile 50 de l'espèce
  *   q75_d : quantile 75 de l'espèce
  *   q95_d : quantile 95 de l'espèce
  *
q97_5_d : quantile 97,5 de l'espèce

Pour les phéno unique, il s'agit d'espèces dont la phéno de migration ne repose que sur un seul évènement. Par exemple, le Puffin majeur, dont la présence en France ne correspond qu'à une partie de sa migration prénuptiale (au sens hémisphère sud, donc durant l'été et l'automne chez nous). Une solution serait de mixer les deux tables et de mettre les phénos unique dans les champs migration prénuptiale ?

Pour le rafraichissement des données, on pensait faire une MAJ annuelle, début janvier, en supprimant une année et en ajoutant la dernière. Marine estime que cela devrait prendre une semaine de temps de calcul.

Pour les vues matérialisées du nombre de données par décade, on te les envoie rapido.

Merci,





Jérémy Dupuy
Responsable de projet « Oiseaux de France »

Service Connaissance

Pôle Protection de la Nature

05.46.82.17.92
Fonderies Royales – CS 90263
17300 ROCHEFORT Cedex



[cid:0792c98f-6f49-492f-85cf-f98438614ba2]
________________________________
De : Fred C ***@***.***>
Envoyé : mardi 24 octobre 2023 21:04
À : lpoaura/BirdAtlasOfFrance ***@***.***>
Cc : Jeremy Dupuy ***@***.***>; Author ***@***.***>
Objet : Re: [lpoaura/BirdAtlasOfFrance] Phénologie de migration pour fiche espèce (Issue #330)


cf. #166<https://github.com/lpoaura/BirdAtlasOfFrance/issues/166>.

Merci.

Pourriez-vous détailler le contenu de ces tables? A quoi correspondent les espèces "à une seule phéno" ne pourrait-on pas n'en faire qu'une vue unique? Quel temps prendra le processus de rafraîchissement de ces données.

Il reste à produire une vue du nombre de données en migration active par décade et par espèce (cf. #166<https://github.com/lpoaura/BirdAtlasOfFrance/issues/166>).

Enfin, il faudra amender le code source du projet avec les requêtes ayant permis l'obtention de ces résultats. On pourra en discuter

**Comment by JeremyDupuy** [comment]
Bonjour Fred,

Pour compléter pour les phéno, la vue matérialisée du nombre de données par décade pour chaque espèce traitées dans les phénos.

lpofrance_mte.pheno_migration_etape7_2_nb_donnees_esp_decade

Bonne journée,


Jérémy Dupuy
Responsable de projet « Oiseaux de France »

Service Connaissance

Pôle Protection de la Nature

05.46.82.17.92
Fonderies Royales – CS 90263
17300 ROCHEFORT Cedex



[cid:2a12e585-66aa-4740-831a-a02bddc1b1ce]
________________________________
De : Jeremy Dupuy ***@***.***>
Envoyé : mercredi 25 octobre 2023 15:43
À : lpoaura/BirdAtlasOfFrance ***@***.***>; lpoaura/BirdAtlasOfFrance ***@***.***>
Cc : Author ***@***.***>
Objet : RE: [lpoaura/BirdAtlasOfFrance] Phénologie de migration pour fiche espèce (Issue #330)

Bonjour Fred,

Les réponses :

Vue matérialisée pheno_migration_etape7_quantiles_choix_traitement_esp_d

  *   cd_nom
  *   traitement : traitement appliqué pour l'espèce déterminant les quantiles
  *   q2_5_printemps_d : quantile 2,5 en décade pour la période de printemps de l'espèce
  *   q5_printemps_d : quantile 5 en décade pour la période de printemps de l'espèce
  *   q25_printemps_d : quantile 25 en décade pour la période de printemps de l'espèce
  *   mediane_printemps_d : quantile 50 en décade pour la période de printemps de l'espèce
  *   q75_printemps_d  : quantile 75 en décade pour la période de printemps de l'espèce
  *   q95_printemps_d : quantile 95 en décade pour la période de printemps de l'espèce
  *   q97_5_printemps_d : quantile 97,5 en décade pour la période de printemps de l'espèce
  *   q2_5_automne_d : quantile 2,5 en décade pour la période d'automne de l'espèce
  *   q5_automne_d : quantile 5 en décade pour la période d'automne de l'espèce
  *   q25_automne_d : quantile 25 en décade pour la période d'automne de l'espèce
  *   mediane_automne_d  : quantile 50 en décade pour la période d'automne de l'espèce
  *   q75_automne_d : quantile 75 en décade pour la période d'automne de l'espèce
  *   q95_automne_d : quantile 95 en décade pour la période d'automne de l'espèce
  *   q97_5_automne_d : quantile 97,5 en décade pour la période d'automne de l'espèce
  *   decade_charniere : décade charnière entre le printemps et l'automne de l'espèce

Vue matérialisée pheno_migration_etape_6_4_quantiles_esp_spe_d

  *   cd_nom
  *   q2_5_d : quantile 2,5 de l'espèce
  *   q5_d : quantile 5 de l'espèce
  *   q25_d : quantile 25 de l'espèce
  *   mediane_d : quantile 50 de l'espèce
  *   q75_d : quantile 75 de l'espèce
  *   q95_d : quantile 95 de l'espèce
  *
q97_5_d : quantile 97,5 de l'espèce

Pour les phéno unique, il s'agit d'espèces dont la phéno de migration ne repose que sur un seul évènement. Par exemple, le Puffin majeur, dont la présence en France ne correspond qu'à une partie de sa migration prénuptiale (au sens hémisphère sud, donc durant l'été et l'automne chez nous). Une solution serait de mixer les deux tables et de mettre les phénos unique dans les champs migration prénuptiale ?

Pour le rafraichissement des données, on pensait faire une MAJ annuelle, début janvier, en supprimant une année et en ajoutant la dernière. Marine estime que cela devrait prendre une semaine de temps de calcul.

Pour les vues matérialisées du nombre de données par décade, on te les envoie rapido.

Merci,





Jérémy Dupuy
Responsable de projet « Oiseaux de France »

Service Connaissance

Pôle Protection de la Nature

05.46.82.17.92
Fonderies Royales – CS 90263
17300 ROCHEFORT Cedex



[cid:0792c98f-6f49-492f-85cf-f98438614ba2]
________________________________
De : Fred C ***@***.***>
Envoyé : mardi 24 octobre 2023 21:04
À : lpoaura/BirdAtlasOfFrance ***@***.***>
Cc : Jeremy Dupuy ***@***.***>; Author ***@***.***>
Objet : Re: [lpoaura/BirdAtlasOfFrance] Phénologie de migration pour fiche espèce (Issue #330)


cf. #166<https://github.com/lpoaura/BirdAtlasOfFrance/issues/166>.

Merci.

Pourriez-vous détailler le contenu de ces tables? A quoi correspondent les espèces "à une seule phéno" ne pourrait-on pas n'en faire qu'une vue unique? Quel temps prendra le processus de rafraîchissement de ces données.

Il reste à produire une vue du nombre de données en migration active par décade et par espèce (cf. #166<https://github.com/lpoaura/BirdAtlasOfFrance/issues/166>).

Enfin, il faudra amender le code source du projet avec les requêtes ayant permis l'obtention de ces résultats. On pourra en discuter

**Comment by lpofredc** [comment]
Graphique et données intégrées
