### ISSUE TITLE
Oiseaux en hiver et donnees "oiseaux des jardins"

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#331]
Bonjour,
La confusion pour certaines especes est importante sur cette enquete. Comment allez-vous proceder ?
Marc

**Comment by lpofredc** [comment]
@JérémyDupuy, des réponses à apporter ?

**Comment by JeremyDupuy** [comment]
Il s'agit pour l'immense majorité des observations, d'espèces très communes donc pas trop grave s'il y a des erreurs.

Pour les espèces plus critiques (friquet, mésange noire), c'est le job des vérificateurs. on part du principe que le jeux de données est bon...

**Comment by mgageo** [comment]
Les vérificateurs n'arrivent pas à traiter toutes les données d'odj et de nombreuses demandes de vérification restent sans réponse ce qui les découragent dans leur activité.
Pour un observateur, une demande avec quelques mois/années de retard est mal perçue.
En cette fin d'année de nombreux sites vont migrer en site miroir ce qui va changer les procédures utilisées par les vérificateurs, leur travail ne sera en plus pas facilité par la dégradation des performances. 
En plus il existe des problèmes de synchronisation entre les sites locaux et faune-france (cf le Moineau friquet est présent en hiver sur la maille E026N674 sans aucune donnée valide dans [fb](https://www.faune-bretagne.org/index.php?m_id=94&p_c=4&p_cc=-1&sp_tg=1&sp_DFrom=18.11.2021&sp_DTo=18.11.2021&sp_DChoice=season&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=12&sp_DSeasonToDay=31&sp_DSeasonToMonth=1&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=495&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=0010&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E026N674&sp_Grid=189&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-5&sp_AltitudeTo=387&sp_CommentValue=&sp_HiddenCommentValue=&sp_ObserverNameString=&sp_ObserverName=0&sp_OnlyAH=0&sp_AtlasCode=1&sp_Ats=-v0000&sp_F=0&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_I=0&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FExportFormat=XLS&sp_ExportModel=1&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=21.02.2022&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher) (les vérificateurs ont bien travaillé) mais avec des données dans [ff](https://www.faune-france.org/index.php?m_id=94&p_c=3&p_cc=-1&sp_tg=1&sp_DFrom=17.11.2021&sp_DTo=25.10.2023&sp_DChoice=season&sp_DSeasonFromDay=1&sp_DSeasonFromMonth=12&sp_DSeasonToDay=31&sp_DSeasonToMonth=1&sp_DOffset=5&sp_SChoice=species&speciesFilter=&sp_S=495&sp_Cat%5Bnever%5D=1&sp_Cat%5Bveryrare%5D=1&sp_Cat%5Brare%5D=1&sp_Cat%5Bunusual%5D=1&sp_Cat%5Bescaped%5D=1&sp_Cat%5Bcommon%5D=1&sp_Cat%5Bverycommon%5D=1&sp_Family=1&sp_cC=00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000&sp_cCO=0&sp_CommuneCounty=36&sp_Commune=13859&sp_Info=&sp_P=0&sp_PChoice=grid&sp_Grid_Info=E026N674&sp_Grid=189&sp_Polygon=&sp_PolygonSaveName=&sp_AltitudeFrom=-12&sp_AltitudeTo=4848&sp_CommentValue=&sp_OnlyAH=0&sp_Ats=-00000&sp_project=&sp_OnlyStoc=&sp_frmListType=&sp_FChoice=list&sp_FDisplay=DATE_PLACE_SPECIES&sp_DFormat=DESC&sp_FOrderListSpecies=ALPHA&sp_FListSpeciesChoice=DATA&sp_DateSynth=25.10.2023&sp_FOrderSynth=ALPHA&sp_FGraphChoice=DATA&sp_FGraphFormat=auto&sp_FAltScale=250&sp_FAltChoice=DATA&sp_FMapFormat=none&submit=Chercher)

**Comment by lpojgc** [comment]
Pour info/mémoire, les données en cours de vérif sont exclues des restitutions.
La discussion dépassant le cadre d'ODF, je clôture le ticket
