### ISSUE TITLE
Fiche-espèce Phénologie de reproduction

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#336]
Hello, dans la fiche-espèce >> diagramme >> période de reproduction >> il y a un histogramme reproduction sous l'histo phénologie Toutes données. Cette phénologie de reproduction devrait être basée sur les données issues de certains codes-atlas mais nous n'avons finalement pas fait ce travail. Il faudra donc supprimer cette figure de la fiche espèce.

**Comment by lpojgc** [comment]
désactiver pour le moment en attendant d'avoir la transmission des codes à utiliser par espèce

**Comment by lpofredc** [comment]
Ok graphique désactivé
