### ISSUE TITLE
Bug affichage Liste d'espèces mailles

### ISSUE THREAD

**Issue by JeremyDupuy** [lpoaura/BirdAtlasOfFrance#338]
Salut,

Sur les cartes de prospections, lorsque je clique sur une maille et Espèces pour voir la liste avant et après 2019, la liste ne s'affiche plus. 
![Annotation 2024-02-06 103823](https://github.com/lpoaura/BirdAtlasOfFrance/assets/112935253/9bc9ce89-588d-4c94-b5d1-20c9c696bfc6)

**Comment by lpofredc** [comment]
Pb corrigé. Pb de correspondance de taxons
