### ISSUE TITLE
Certificat pour https://www.oiseauxdefrance.org/api/v1/search/taxa?limit=1600

### ISSUE THREAD

**Issue by mgageo** [lpoaura/BirdAtlasOfFrance#348]
La requête échoue car le certificat https n'est plus valide depuis le "Wed, 07 Jun 2023 01:07:34 GMT"

**Comment by lpofredc** [comment]
Ok, merci @mgageo pour ce retour, l'URL officielle est sans le www, avec un certificat valide.

https://oiseauxdefrance.org/api/v1/search/taxa?limit=1600

Mais c'est un problème a gérer sur la configuration DNS du site.

**Comment by mgageo** [comment]
Effectivement c'est bon sans le "www".
Une requête avec limit=1700 répond "Internal Server Error", ce qui n'est pas du json.
Comment connaître la valeur maximale de limit ?

**Comment by lpofredc** [comment]
C'est une erreur provoqué par un taxon dont les informations principales (nom français, nom scientifique, nom anglais, etc) étaient incomplètes (Outarde barbue).

C'est corrigé.

Pas de limites en soit sur cette API.

Je ferme l'issue
