### ISSUE TITLE
API indices de complétude de l'Atlas

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#40]
### Résultat
![indices_completude_Atlas](https://user-images.githubusercontent.com/57666163/107363091-f5402000-6ad9-11eb-90e6-036646503645.png)
ℹ️ Le pourcentage central correspond à la moyenne d'avancement de l'ensemble des mailles.

**Comment by eguilley** [comment]
⚠️ **Manquent** : 
- Indice de complétude global (au milieu du diagramme)
- Déclinaison des résultats selon la période de repro et la période d'hivernage

**Comment by lpofredc** [comment]
La déclinaison des résultats selon la période doit être fourni par la même API ou son utilisation se fait à un emplacement différent?

**Comment by eguilley** [comment]
Il s'agit de la même API, l'encart suivant doit être mis à jour instantanément selon la période choisie dans la liste déroulante : 
![indice-de-complétude](https://user-images.githubusercontent.com/57666163/113681173-f51b6580-96c1-11eb-9de6-f0e99ffad0a5.png)

**Comment by eguilley** [comment]
Je pense qu'il y a également une erreur dans les résultats... seulement 2% de mailles entre 0 et 25% de complétude alors qu'en dehors d'AuRA elles sont toutes à 0 actuellement ?
![carte-prospection](https://user-images.githubusercontent.com/57666163/113684286-5c86e480-96c5-11eb-875d-190b9ce650fb.png)

**Comment by lpofredc** [comment]
Généralisation de l'API `knowledge_level`. Si pas de querystring > alors on a le résultat global toutes périodes confondues. options (qs) dispos:
- period: [allperiod,wintering,breeding]
- id_area : id_area

`/api/v1/knowledge_level?id_area=<id_area>&period=<period>`

cf.
