### ISSUE TITLE
API cartes de répartition pour une espèce donnée - Pour les 3 périodes (toutes saisons/repro/hiver)

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#45]
⚠️ Besoin du centroïde des mailles (et non de la géométrie) !

🌞 Période de reproduction : centroïde coloré en fonction du statut nicheur (possible/probable/certain)
❄️ Période d'hivernage : centroïde coloré si présence
🍃 Toutes saisons : centroïde coloré si présence

**Comment by lpojgc** [comment]
Besoin du centroïde ET de la maille (selon le niveau de zoom)

**Comment by eguilley** [comment]
@lpofredc : cf. commentaire de Julien ci-dessus => Pouvoir choisir la géométrie en appelant l'API (maille ou centroïde)

**Comment by lpofredc** [comment]
> @lpofredc : cf. commentaire de Julien ci-dessus => Pouvoir choisir la géométrie quand on appelle l'API (maille ou centroïde)

Fixé dans #138
