### ISSUE TITLE
API contours des régions et départements de la France métropolitaine

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#56]
Objectif : pouvoir les injecter en geojson sur la carte de prospection

**Comment by lpofredc** [comment]
see [`/api/v1/lareas/type/{type_code}` API docs](http://localhost:8888/docs#/ref_geo/list_lareas_api_v1_lareas_type__type_code__get)

**Comment by eguilley** [comment]
@lpofredc : checker si l'API fonctionne bien (comme discuté en réunion)

**Comment by lpofredc** [comment]
Fixed in #137

**Comment by eguilley** [comment]
### Nécessité de simplifier les géométries si on souhaite afficher toutes les régions avec l'API `/api/v1/lareas/type/{type_code}`
