### ISSUE TITLE
API Obtenir l'emprise du zonage dans lequel on se trouve à partir d'une géolocalisation

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#67]

**Comment by lpofredc** [comment]
see [`/api/v1/lareas/position`API Docs](http://localhost:8888/docs#/ref_geo/get_area_by_coordinates_api_v1_lareas_position_get) from commit https://github.com/lpoaura/BirdAtlasOfFrance/commit/1625a1e46cee3a31b3e967f01c19c577207407f5

**Comment by eguilley** [comment]
@lpofredc : Si la géolocalisation ne pointe sur aucun territoire de l'Atlas **=> Renvoyer un geojson vide** (plutôt qu'une erreur 404)

**Comment by lpofredc** [comment]
Intégré dans la PR #214. A gérer côté frontend par un check sur `data` dans l'appel à l'API.

**Comment by eguilley** [comment]
@lpofredc tu l'as déjà géré côté frontend non ?
