### ISSUE TITLE
API liste des points EPOC ODF d'une maille

### ISSUE THREAD

**Issue by eguilley** [lpoaura/BirdAtlasOfFrance#72]
ℹ️ Données nécessaires : **toutes les données du shape** (sauf `DEPART_TOT` qui est un doublon de `DEPARTE`)

### Résultat
![liste-points-EPOC](https://user-images.githubusercontent.com/57666163/113678570-1595f080-96bf-11eb-9a3b-ae8954dab11c.png)
### Au clic sur un point EPOC
![clic-point-EPOC](https://user-images.githubusercontent.com/57666163/113679183-c69c8b00-96bf-11eb-8bc4-98a160786495.png)

**Comment by lpofredc** [comment]
Ajout d'une option de filtrage par statuts : `?envelope=...&status=Officiel|Reserve`

**Comment by eguilley** [comment]
@lpofredc : Il manque la localisation du point EPOC. Besoin de structurer les données retournées de cette manière (comme dans le geojson) :
```json
[
  {
    "geometry": {
      "coordinates": [
        "string"
      ],
    },
    "properties": {
      "id_epoc": 0,
      "id_ff": "string",
      "status": "string",
      "rang_rsv": 0
    },
  },
  ...
]
```
